In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
import optuna
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import classification_report

c:\Users\caleb\anaconda3\envs\iris-fisher\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
random_state = 42

In [3]:
df = pd.read_csv('../Milestone 3 EDA/credit_card_cleaned.csv')
df

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

## Baseline

In [4]:
X = df.drop(columns='Class')
y = df['Class']

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    test_size=0.2, 
                                                    stratify=y,  # Maintains class distribution
                                                    random_state=random_state
                                                    )

### Default settings on RF

In [6]:
# Train using optimal parameters
model = RandomForestClassifier(
    random_state=random_state,
    n_jobs=-1,
)
model.fit(X_train, y_train)

RandomForestClassifier(n_jobs=-1, random_state=42)

In [7]:
y_pred = model.predict(X_test)

In [8]:
print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.94      0.82      0.87        98

    accuracy                           1.00     56962
   macro avg       0.97      0.91      0.94     56962
weighted avg       1.00      1.00      1.00     56962

In [9]:
baseline_model_report_df = classification_report(y_test, y_pred, output_dict=True)

### Class Weight Balanced

In [10]:
# Train using optimal parameters
model = RandomForestClassifier(
    class_weight='balanced',
    random_state=random_state,
    n_jobs=-1
)
model.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', n_jobs=-1, random_state=42)

In [11]:
y_pred = model.predict(X_test)

In [12]:
print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.96      0.74      0.84        98

    accuracy                           1.00     56962
   macro avg       0.98      0.87      0.92     56962
weighted avg       1.00      1.00      1.00     56962

In [13]:
baseline_balanced_model_report_df = classification_report(y_test, y_pred, output_dict=True)

## Undersamplgin

In [14]:
fraud = df[df['Class'] == 1]
non_fraud = df[df['Class'] == 0]
len(fraud), len(non_fraud)

(492, 284315)

In [15]:
# Undersample majority class to a 1:10 ratio
non_fraud_downsampled = non_fraud.sample(n=len(fraud) * 10, random_state=random_state)
non_fraud_downsampled

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
138028,82450.0,1.314539,0.590643,-0.666593,0.716564,0.301978,-1.125467,0.388881,-0.288390,-0.132137,...,-0.170307,-0.429655,-0.141341,-0.200195,0.639491,0.399476,-0.034321,0.031692,0.76,0
63099,50554.0,-0.798672,1.185093,0.904547,0.694584,0.219041,-0.319295,0.495236,0.139269,-0.760214,...,0.202287,0.578699,-0.092245,0.013723,-0.246466,-0.380057,-0.396030,-0.112901,4.18,0
73411,55125.0,-0.391128,-0.245540,1.122074,-1.308725,-0.639891,0.008678,-0.701304,-0.027315,-2.628854,...,-0.133485,0.117403,-0.191748,-0.488642,-0.309774,0.008100,0.163716,0.239582,15.00,0
164247,116572.0,-0.060302,1.065093,-0.987421,-0.029567,0.176376,-1.348539,0.775644,0.134843,-0.149734,...,0.355576,0.907570,-0.018454,-0.126269,-0.339923,-0.150285,-0.023634,0.042330,57.00,0
148999,90434.0,1.848433,0.373364,0.269272,3.866438,0.088062,0.970447,-0.721945,0.235983,0.683491,...,0.103563,0.620954,0.197077,0.692392,-0.206530,-0.021328,-0.019823,-0.042682,0.00,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249845,154606.0,-1.235823,-0.571536,1.620984,-2.648022,0.431772,1.315577,-0.258094,0.687327,-1.039031,...,0.163828,0.220473,-0.023553,-1.685719,0.301464,-0.260192,0.268870,0.102644,88.30,0
131485,79621.0,1.227929,0.065334,0.043523,0.109012,-0.394905,-1.307819,0.349677,-0.310790,-0.030846,...,-0.424623,-1.375408,0.178609,0.395001,0.078121,0.619247,-0.109945,0.009712,44.94,0
96599,65844.0,-0.878702,0.077973,0.345555,-1.646600,-0.090887,-0.930793,-0.136898,0.407723,-1.456907,...,0.367227,0.880295,-0.150938,0.039828,-0.197562,-0.330629,0.274606,0.090629,15.00,0
164556,116806.0,-1.296659,0.282590,1.651779,-1.503733,-1.575132,-0.079848,-0.673041,0.332639,0.226605,...,-0.141780,0.269977,-0.043272,-0.036735,-0.731235,0.545507,-0.173457,0.059645,45.51,0
204391,135255.0,2.086587,0.259341,-2.621745,0.690682,0.856012,-0.794831,0.185421,-0.220086,0.851101,...,-0.084253,0.082433,-0.164890,-1.211734,0.315994,0.795641,-0.037682,-0.023651,10.70,0

In [16]:
# Combine and shuffle
df_reduced = pd.concat([fraud, non_fraud_downsampled]).sample(frac=1).reset_index(drop=True)
df_reduced

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,159595.0,0.058198,-0.568091,0.572386,-2.026601,-1.712810,-0.404623,-0.854774,0.309016,-1.855603,...,0.308923,1.264259,0.186943,0.020606,-0.771501,-0.014161,0.054398,0.060696,76.50,0
1,170624.0,-6.729411,6.202271,-4.858542,-1.077134,-2.690236,-1.862082,-1.962344,3.176962,1.959044,...,0.269847,0.973180,0.576281,-0.033582,0.266224,-0.159472,0.893651,0.850891,2.23,0
2,137964.0,0.000369,0.410913,-1.752857,-1.679642,1.872037,-1.511905,2.368843,-0.858596,-0.386364,...,0.534175,1.839547,-0.145707,-0.282628,-0.977345,-0.123117,-0.024836,0.100298,94.00,0
3,26961.0,-23.237920,13.487386,-25.188773,6.261733,-17.345188,-4.534989,-17.100492,15.374630,-3.845567,...,1.769708,-1.691973,-1.045673,0.143386,1.611577,-0.221576,1.481233,0.438125,99.99,1
4,135095.0,0.232512,0.938944,-4.647780,3.079844,-1.902655,-1.041408,-1.020407,0.547069,-1.105990,...,0.911373,1.042929,0.999394,0.901260,-0.452093,0.192959,0.180859,-0.029315,345.00,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5407,75353.0,-0.347115,0.642984,1.437025,0.043874,0.016548,-0.333314,0.573444,0.031889,-0.359167,...,0.254176,0.717301,-0.161641,0.128705,0.057913,0.506090,-0.000468,0.016406,33.80,0
5408,67859.0,-0.381367,1.056180,1.307479,-0.051254,0.053216,-0.668698,0.578171,0.097346,-0.592646,...,-0.217722,-0.610316,-0.025837,0.267104,-0.204733,0.055972,0.239640,0.087102,1.99,0
5409,114782.0,-6.171083,3.664822,-4.206587,-0.590427,-1.965903,-1.708880,-1.165982,2.361165,1.870738,...,0.090239,0.827777,-0.068012,1.162462,-0.047745,-0.235597,0.923786,1.317223,1.00,0
5410,129764.0,-2.434004,3.225947,-6.596282,3.593161,-1.079452,-1.739741,-0.047420,0.301424,-1.779434,...,-0.035491,-0.419178,0.157436,-0.714849,0.468859,-0.348522,0.420036,-0.327643,362.55,1
5411,70972.0,0.723838,-0.876518,1.546599,1.802307,-1.288212,1.089742,-0.884291,0.542340,1.383544,...,-0.013776,0.087984,-0.124104,0.238693,0.331654,-0.335056,0.079704,0.048365,152.01,0

In [17]:
X = df_reduced.drop(columns='Class')
y = df_reduced['Class']

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    test_size=0.2, 
                                                    stratify=y,  # Maintains class distribution
                                                    random_state=random_state
                                                    )

In [19]:
cv = StratifiedKFold(n_splits=5)

### Recall as metric

In [20]:
# Parameter tuning
def objective(trial):
    n_estimators = trial.suggest_int("n_estimators", 10, 200)
    max_depth = trial.suggest_int("max_depth", 2, 32, log=True)
    min_samples_split = trial.suggest_int("min_samples_split", 2, 10)
    
    model = RandomForestClassifier(
        class_weight='balanced',
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        random_state=random_state
    )
    
    scores = cross_val_score(
        model, 
        X=X_train, 
        y=y_train, 
        cv=cv,
        scoring='recall',
        n_jobs=-1,
    )
    return scores.mean()


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

top_5_recall_df = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_recall_df)

[I 2026-04-14 20:29:13,125] A new study created in memory with name: no-name-48d584a9-9ea2-48a3-bb33-e7bf5a264451
[I 2026-04-14 20:29:15,083] Trial 0 finished with value: 0.8376501135994807 and parameters: {'n_estimators': 67, 'max_depth': 12, 'min_samples_split': 6}. Best is trial 0 with value: 0.8376501135994807.
[I 2026-04-14 20:29:16,468] Trial 1 finished with value: 0.8579032781564427 and parameters: {'n_estimators': 94, 'max_depth': 3, 'min_samples_split': 8}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:18,044] Trial 2 finished with value: 0.8325219084712755 and parameters: {'n_estimators': 185, 'max_depth': 2, 'min_samples_split': 8}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:20,350] Trial 3 finished with value: 0.8452450503083415 and parameters: {'n_estimators': 87, 'max_depth': 17, 'min_samples_split': 10}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:20,554] Trial 4 finished with value: 0.837585199610516 and parameters: {'n_estimators': 53, 'max_depth': 2, 'min_samples_split': 3}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:21,082] Trial 5 finished with value: 0.8325219084712755 and parameters: {'n_estimators': 156, 'max_depth': 2, 'min_samples_split': 5}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:22,802] Trial 6 finished with value: 0.8427134047387213 and parameters: {'n_estimators': 176, 'max_depth': 11, 'min_samples_split': 4}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:24,201] Trial 7 finished with value: 0.8452450503083415 and parameters: {'n_estimators': 195, 'max_depth': 6, 'min_samples_split': 2}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:25,406] Trial 8 finished with value: 0.8427134047387213 and parameters: {'n_estimators': 127, 'max_depth': 27, 'min_samples_split': 8}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:25,796] Trial 9 finished with value: 0.8300227198961375 and parameters: {'n_estimators': 36, 'max_depth': 14, 'min_samples_split': 2}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:25,906] Trial 10 finished with value: 0.850308341447582 and parameters: {'n_estimators': 13, 'max_depth': 4, 'min_samples_split': 8}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:25,999] Trial 11 finished with value: 0.850308341447582 and parameters: {'n_estimators': 13, 'max_depth': 4, 'min_samples_split': 8}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:26,608] Trial 12 finished with value: 0.8553716325868225 and parameters: {'n_estimators': 117, 'max_depth': 4, 'min_samples_split': 10}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:27,233] Trial 13 finished with value: 0.8553716325868225 and parameters: {'n_estimators': 122, 'max_depth': 4, 'min_samples_split': 10}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:27,956] Trial 14 finished with value: 0.8452450503083415 and parameters: {'n_estimators': 102, 'max_depth': 6, 'min_samples_split': 9}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:28,549] Trial 15 finished with value: 0.8553716325868225 and parameters: {'n_estimators': 141, 'max_depth': 3, 'min_samples_split': 7}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:29,254] Trial 16 finished with value: 0.8427134047387213 and parameters: {'n_estimators': 86, 'max_depth': 8, 'min_samples_split': 10}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:29,709] Trial 17 finished with value: 0.8528399870172023 and parameters: {'n_estimators': 108, 'max_depth': 3, 'min_samples_split': 6}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:30,355] Trial 18 finished with value: 0.8553716325868225 and parameters: {'n_estimators': 156, 'max_depth': 3, 'min_samples_split': 9}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:30,812] Trial 19 finished with value: 0.8553716325868225 and parameters: {'n_estimators': 78, 'max_depth': 5, 'min_samples_split': 9}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:31,701] Trial 20 finished with value: 0.8452450503083415 and parameters: {'n_estimators': 106, 'max_depth': 8, 'min_samples_split': 7}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:32,326] Trial 21 finished with value: 0.8553716325868225 and parameters: {'n_estimators': 118, 'max_depth': 4, 'min_samples_split': 10}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:32,891] Trial 22 finished with value: 0.8553716325868225 and parameters: {'n_estimators': 135, 'max_depth': 3, 'min_samples_split': 10}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:33,797] Trial 23 finished with value: 0.8528399870172023 and parameters: {'n_estimators': 149, 'max_depth': 5, 'min_samples_split': 9}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:34,185] Trial 24 finished with value: 0.8325219084712755 and parameters: {'n_estimators': 119, 'max_depth': 2, 'min_samples_split': 7}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:34,623] Trial 25 finished with value: 0.8553716325868226 and parameters: {'n_estimators': 101, 'max_depth': 3, 'min_samples_split': 9}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:34,919] Trial 26 finished with value: 0.8579032781564427 and parameters: {'n_estimators': 61, 'max_depth': 3, 'min_samples_split': 9}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:35,123] Trial 27 finished with value: 0.837585199610516 and parameters: {'n_estimators': 55, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:35,294] Trial 28 finished with value: 0.8477766958779618 and parameters: {'n_estimators': 35, 'max_depth': 3, 'min_samples_split': 9}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:35,591] Trial 29 finished with value: 0.8325219084712755 and parameters: {'n_estimators': 94, 'max_depth': 2, 'min_samples_split': 7}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:36,249] Trial 30 finished with value: 0.8427134047387213 and parameters: {'n_estimators': 71, 'max_depth': 10, 'min_samples_split': 5}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:36,563] Trial 31 finished with value: 0.8579032781564427 and parameters: {'n_estimators': 68, 'max_depth': 3, 'min_samples_split': 9}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:36,825] Trial 32 finished with value: 0.8579032781564427 and parameters: {'n_estimators': 61, 'max_depth': 3, 'min_samples_split': 8}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:37,012] Trial 33 finished with value: 0.837585199610516 and parameters: {'n_estimators': 58, 'max_depth': 2, 'min_samples_split': 8}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:37,277] Trial 34 finished with value: 0.850308341447582 and parameters: {'n_estimators': 37, 'max_depth': 5, 'min_samples_split': 8}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:37,525] Trial 35 finished with value: 0.8350535540408958 and parameters: {'n_estimators': 67, 'max_depth': 2, 'min_samples_split': 8}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:37,727] Trial 36 finished with value: 0.8553716325868225 and parameters: {'n_estimators': 45, 'max_depth': 3, 'min_samples_split': 7}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:37,990] Trial 37 finished with value: 0.8325219084712755 and parameters: {'n_estimators': 75, 'max_depth': 2, 'min_samples_split': 9}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:38,803] Trial 38 finished with value: 0.8376501135994807 and parameters: {'n_estimators': 83, 'max_depth': 26, 'min_samples_split': 5}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:39,271] Trial 39 finished with value: 0.8477766958779618 and parameters: {'n_estimators': 62, 'max_depth': 6, 'min_samples_split': 6}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:39,443] Trial 40 finished with value: 0.837585199610516 and parameters: {'n_estimators': 46, 'max_depth': 2, 'min_samples_split': 8}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:39,863] Trial 41 finished with value: 0.8579032781564427 and parameters: {'n_estimators': 94, 'max_depth': 3, 'min_samples_split': 9}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:40,238] Trial 42 finished with value: 0.8579032781564427 and parameters: {'n_estimators': 89, 'max_depth': 3, 'min_samples_split': 9}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:40,614] Trial 43 finished with value: 0.8528399870172022 and parameters: {'n_estimators': 67, 'max_depth': 4, 'min_samples_split': 8}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:41,051] Trial 44 finished with value: 0.8553716325868226 and parameters: {'n_estimators': 96, 'max_depth': 3, 'min_samples_split': 10}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:41,222] Trial 45 finished with value: 0.8528399870172023 and parameters: {'n_estimators': 26, 'max_depth': 4, 'min_samples_split': 9}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:41,408] Trial 46 finished with value: 0.837585199610516 and parameters: {'n_estimators': 49, 'max_depth': 2, 'min_samples_split': 8}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:42,223] Trial 47 finished with value: 0.8376501135994807 and parameters: {'n_estimators': 79, 'max_depth': 20, 'min_samples_split': 4}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:42,628] Trial 48 finished with value: 0.8528399870172022 and parameters: {'n_estimators': 64, 'max_depth': 5, 'min_samples_split': 10}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:43,065] Trial 49 finished with value: 0.8579032781564427 and parameters: {'n_estimators': 92, 'max_depth': 3, 'min_samples_split': 8}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:43,444] Trial 50 finished with value: 0.8325219084712755 and parameters: {'n_estimators': 112, 'max_depth': 2, 'min_samples_split': 9}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:43,832] Trial 51 finished with value: 0.8579032781564427 and parameters: {'n_estimators': 88, 'max_depth': 3, 'min_samples_split': 9}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:44,239] Trial 52 finished with value: 0.8503083414475819 and parameters: {'n_estimators': 76, 'max_depth': 4, 'min_samples_split': 9}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:44,633] Trial 53 finished with value: 0.8579032781564427 and parameters: {'n_estimators': 85, 'max_depth': 3, 'min_samples_split': 10}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:45,168] Trial 54 finished with value: 0.8553716325868225 and parameters: {'n_estimators': 100, 'max_depth': 4, 'min_samples_split': 7}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:45,436] Trial 55 finished with value: 0.8579032781564427 and parameters: {'n_estimators': 59, 'max_depth': 3, 'min_samples_split': 9}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:45,840] Trial 56 finished with value: 0.8325219084712755 and parameters: {'n_estimators': 128, 'max_depth': 2, 'min_samples_split': 10}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:46,297] Trial 57 finished with value: 0.8528399870172023 and parameters: {'n_estimators': 111, 'max_depth': 3, 'min_samples_split': 9}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:46,687] Trial 58 finished with value: 0.8528399870172022 and parameters: {'n_estimators': 72, 'max_depth': 4, 'min_samples_split': 8}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:46,842] Trial 59 finished with value: 0.850308341447582 and parameters: {'n_estimators': 21, 'max_depth': 5, 'min_samples_split': 7}. Best is trial 1 with value: 0.8579032781564427.
[I 2026-04-14 20:29:47,092] Trial 60 finished with value: 0.860434923726063 and parameters: {'n_estimators': 51, 'max_depth': 3, 'min_samples_split': 9}. Best is trial 60 with value: 0.860434923726063.
[I 2026-04-14 20:29:47,340] Trial 61 finished with value: 0.8579032781564427 and parameters: {'n_estimators': 53, 'max_depth': 3, 'min_samples_split': 9}. Best is trial 60 with value: 0.860434923726063.
[I 2026-04-14 20:29:47,573] Trial 62 finished with value: 0.8503083414475819 and parameters: {'n_estimators': 39, 'max_depth': 4, 'min_samples_split': 9}. Best is trial 60 with value: 0.860434923726063.
[I 2026-04-14 20:29:47,963] Trial 63 finished with value: 0.8579032781564427 and parameters: {'n_estimators': 82, 'max_depth': 3, 'min_samples_split': 10}. Best is trial 60 with value: 0.860434923726063.
[I 2026-04-14 20:29:48,278] Trial 64 finished with value: 0.8325219084712755 and parameters: {'n_estimators': 90, 'max_depth': 2, 'min_samples_split': 8}. Best is trial 60 with value: 0.860434923726063.
[I 2026-04-14 20:29:49,106] Trial 65 finished with value: 0.8528399870172023 and parameters: {'n_estimators': 198, 'max_depth': 3, 'min_samples_split': 8}. Best is trial 60 with value: 0.860434923726063.
[I 2026-04-14 20:29:49,357] Trial 66 finished with value: 0.8350535540408958 and parameters: {'n_estimators': 69, 'max_depth': 2, 'min_samples_split': 9}. Best is trial 60 with value: 0.860434923726063.
[I 2026-04-14 20:29:49,605] Trial 67 finished with value: 0.8579032781564427 and parameters: {'n_estimators': 53, 'max_depth': 3, 'min_samples_split': 10}. Best is trial 60 with value: 0.860434923726063.
[I 2026-04-14 20:29:50,400] Trial 68 finished with value: 0.8452450503083415 and parameters: {'n_estimators': 99, 'max_depth': 7, 'min_samples_split': 9}. Best is trial 60 with value: 0.860434923726063.
[I 2026-04-14 20:29:50,509] Trial 69 finished with value: 0.837585199610516 and parameters: {'n_estimators': 31, 'max_depth': 2, 'min_samples_split': 3}. Best is trial 60 with value: 0.860434923726063.
[I 2026-04-14 20:29:52,115] Trial 70 finished with value: 0.8452450503083415 and parameters: {'n_estimators': 173, 'max_depth': 14, 'min_samples_split': 8}. Best is trial 60 with value: 0.860434923726063.
[I 2026-04-14 20:29:52,600] Trial 71 finished with value: 0.8528399870172023 and parameters: {'n_estimators': 107, 'max_depth': 3, 'min_samples_split': 8}. Best is trial 60 with value: 0.860434923726063.
[I 2026-04-14 20:29:53,021] Trial 72 finished with value: 0.8579032781564427 and parameters: {'n_estimators': 93, 'max_depth': 3, 'min_samples_split': 9}. Best is trial 60 with value: 0.860434923726063.
[I 2026-04-14 20:29:53,254] Trial 73 finished with value: 0.8503083414475819 and parameters: {'n_estimators': 42, 'max_depth': 4, 'min_samples_split': 7}. Best is trial 60 with value: 0.860434923726063.
[I 2026-04-14 20:29:53,583] Trial 74 finished with value: 0.8579032781564427 and parameters: {'n_estimators': 79, 'max_depth': 3, 'min_samples_split': 8}. Best is trial 60 with value: 0.860434923726063.
[I 2026-04-14 20:29:53,875] Trial 75 finished with value: 0.8579032781564427 and parameters: {'n_estimators': 63, 'max_depth': 3, 'min_samples_split': 8}. Best is trial 60 with value: 0.860434923726063.
[I 2026-04-14 20:29:54,252] Trial 76 finished with value: 0.8503083414475819 and parameters: {'n_estimators': 73, 'max_depth': 4, 'min_samples_split': 9}. Best is trial 60 with value: 0.860434923726063.
[I 2026-04-14 20:29:54,533] Trial 77 finished with value: 0.8325219084712755 and parameters: {'n_estimators': 92, 'max_depth': 2, 'min_samples_split': 9}. Best is trial 60 with value: 0.860434923726063.
[I 2026-04-14 20:29:54,768] Trial 78 finished with value: 0.8579032781564427 and parameters: {'n_estimators': 50, 'max_depth': 3, 'min_samples_split': 10}. Best is trial 60 with value: 0.860434923726063.
[I 2026-04-14 20:29:55,348] Trial 79 finished with value: 0.8528399870172023 and parameters: {'n_estimators': 86, 'max_depth': 5, 'min_samples_split': 8}. Best is trial 60 with value: 0.860434923726063.
[I 2026-04-14 20:29:55,536] Trial 80 finished with value: 0.837585199610516 and parameters: {'n_estimators': 56, 'max_depth': 2, 'min_samples_split': 7}. Best is trial 60 with value: 0.860434923726063.
[I 2026-04-14 20:29:56,031] Trial 81 finished with value: 0.8553716325868226 and parameters: {'n_estimators': 103, 'max_depth': 3, 'min_samples_split': 9}. Best is trial 60 with value: 0.860434923726063.
[I 2026-04-14 20:29:56,408] Trial 82 finished with value: 0.8579032781564427 and parameters: {'n_estimators': 88, 'max_depth': 3, 'min_samples_split': 9}. Best is trial 60 with value: 0.860434923726063.
[I 2026-04-14 20:29:56,921] Trial 83 finished with value: 0.8553716325868225 and parameters: {'n_estimators': 97, 'max_depth': 4, 'min_samples_split': 9}. Best is trial 60 with value: 0.860434923726063.
[I 2026-04-14 20:29:57,432] Trial 84 finished with value: 0.8553716325868225 and parameters: {'n_estimators': 114, 'max_depth': 3, 'min_samples_split': 8}. Best is trial 60 with value: 0.860434923726063.
[I 2026-04-14 20:29:57,820] Trial 85 finished with value: 0.8579032781564427 and parameters: {'n_estimators': 81, 'max_depth': 3, 'min_samples_split': 10}. Best is trial 60 with value: 0.860434923726063.
[I 2026-04-14 20:29:58,114] Trial 86 finished with value: 0.8579032781564427 and parameters: {'n_estimators': 64, 'max_depth': 3, 'min_samples_split': 9}. Best is trial 60 with value: 0.860434923726063.
[I 2026-04-14 20:29:58,379] Trial 87 finished with value: 0.8350535540408958 and parameters: {'n_estimators': 74, 'max_depth': 2, 'min_samples_split': 10}. Best is trial 60 with value: 0.860434923726063.
[I 2026-04-14 20:29:58,845] Trial 88 finished with value: 0.8528399870172022 and parameters: {'n_estimators': 89, 'max_depth': 4, 'min_samples_split': 8}. Best is trial 60 with value: 0.860434923726063.
[I 2026-04-14 20:29:59,158] Trial 89 finished with value: 0.8579032781564427 and parameters: {'n_estimators': 60, 'max_depth': 3, 'min_samples_split': 9}. Best is trial 60 with value: 0.860434923726063.
[I 2026-04-14 20:29:59,504] Trial 90 finished with value: 0.8325219084712755 and parameters: {'n_estimators': 107, 'max_depth': 2, 'min_samples_split': 9}. Best is trial 60 with value: 0.860434923726063.
[I 2026-04-14 20:29:59,864] Trial 91 finished with value: 0.8579032781564427 and parameters: {'n_estimators': 82, 'max_depth': 3, 'min_samples_split': 10}. Best is trial 60 with value: 0.860434923726063.
[I 2026-04-14 20:30:00,242] Trial 92 finished with value: 0.8579032781564427 and parameters: {'n_estimators': 85, 'max_depth': 3, 'min_samples_split': 10}. Best is trial 60 with value: 0.860434923726063.
[I 2026-04-14 20:30:00,619] Trial 93 finished with value: 0.8528399870172022 and parameters: {'n_estimators': 69, 'max_depth': 4, 'min_samples_split': 10}. Best is trial 60 with value: 0.860434923726063.
[I 2026-04-14 20:30:01,027] Trial 94 finished with value: 0.8553716325868226 and parameters: {'n_estimators': 95, 'max_depth': 3, 'min_samples_split': 8}. Best is trial 60 with value: 0.860434923726063.
[I 2026-04-14 20:30:01,462] Trial 95 finished with value: 0.8553716325868226 and parameters: {'n_estimators': 101, 'max_depth': 3, 'min_samples_split': 9}. Best is trial 60 with value: 0.860434923726063.
[I 2026-04-14 20:30:01,869] Trial 96 finished with value: 0.8503083414475819 and parameters: {'n_estimators': 77, 'max_depth': 4, 'min_samples_split': 9}. Best is trial 60 with value: 0.860434923726063.

,number,value,datetime_start,datetime_complete,duration,params_max_depth,params_min_samples_split,params_n_estimators,state
60,60,0.860435,2026-04-14 20:29:46.842733,2026-04-14 20:29:47.092685,0 days 00:00:00.249952,3,9,51,COMPLETE
1,1,0.857903,2026-04-14 20:29:15.083652,2026-04-14 20:29:16.468687,0 days 00:00:01.385035,3,8,94,COMPLETE
32,32,0.857903,2026-04-14 20:29:36.563653,2026-04-14 20:29:36.825955,0 days 00:00:00.262302,3,8,61,COMPLETE
26,26,0.857903,2026-04-14 20:29:34.623611,2026-04-14 20:29:34.919969,0 days 00:00:00.296358,3,9,61,COMPLETE
74,74,0.857903,2026-04-14 20:29:53.255781,2026-04-14 20:29:53.583631,0 days 00:00:00.327850,3,8,79,COMPLETE

In [21]:
# Train using optimal parameters
model_1 = RandomForestClassifier(
    class_weight='balanced',
    n_estimators=top_5_recall_df.head(1)['params_n_estimators'].item(),
    max_depth=top_5_recall_df.head(1)['params_max_depth'].item(),
    min_samples_split=top_5_recall_df.head(1)['params_min_samples_split'].item(),
    random_state=random_state
)
model_1.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', max_depth=3,
                       min_samples_split=9, n_estimators=51, random_state=42)

In [22]:
y_pred = model_1.predict(X_test)

In [23]:
print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       985
           1       0.94      0.91      0.92        98

    accuracy                           0.99      1083
   macro avg       0.96      0.95      0.96      1083
weighted avg       0.99      0.99      0.99      1083

In [24]:
recall_model_report_df = classification_report(y_test, y_pred, output_dict=True)

## F1 as metric

In [25]:
# Parameter tuning
def objective(trial):
    n_estimators = trial.suggest_int("n_estimators", 10, 200)
    max_depth = trial.suggest_int("max_depth", 2, 32, log=True)
    min_samples_split = trial.suggest_int("min_samples_split", 2, 10)
    
    model = RandomForestClassifier(
        class_weight='balanced',
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        random_state=random_state
    )
    
    scores = cross_val_score(
        model, 
        X=X_train, 
        y=y_train, 
        cv=cv,
        scoring='f1',
        n_jobs=-1,
    )
    return scores.mean()


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

top_5_f1_df = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_f1_df)

[I 2026-04-14 20:30:03,645] A new study created in memory with name: no-name-84236084-9cd3-4b5e-b2a6-b972d61141bb
[I 2026-04-14 20:30:04,094] Trial 0 finished with value: 0.9021505069256033 and parameters: {'n_estimators': 55, 'max_depth': 7, 'min_samples_split': 10}. Best is trial 0 with value: 0.9021505069256033.
[I 2026-04-14 20:30:05,954] Trial 1 finished with value: 0.9043444307494408 and parameters: {'n_estimators': 197, 'max_depth': 20, 'min_samples_split': 8}. Best is trial 1 with value: 0.9043444307494408.
[I 2026-04-14 20:30:06,342] Trial 2 finished with value: 0.8923152190852353 and parameters: {'n_estimators': 117, 'max_depth': 2, 'min_samples_split': 5}. Best is trial 1 with value: 0.9043444307494408.
[I 2026-04-14 20:30:08,216] Trial 3 finished with value: 0.9055778789627549 and parameters: {'n_estimators': 195, 'max_depth': 15, 'min_samples_split': 7}. Best is trial 3 with value: 0.9055778789627549.
[I 2026-04-14 20:30:09,565] Trial 4 finished with value: 0.9043444307494408 and parameters: {'n_estimators': 145, 'max_depth': 25, 'min_samples_split': 9}. Best is trial 3 with value: 0.9055778789627549.
[I 2026-04-14 20:30:10,285] Trial 5 finished with value: 0.9070108555635166 and parameters: {'n_estimators': 76, 'max_depth': 29, 'min_samples_split': 7}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:10,458] Trial 6 finished with value: 0.871849439718827 and parameters: {'n_estimators': 50, 'max_depth': 2, 'min_samples_split': 7}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:11,085] Trial 7 finished with value: 0.9018196759362145 and parameters: {'n_estimators': 90, 'max_depth': 5, 'min_samples_split': 7}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:11,193] Trial 8 finished with value: 0.8892640106936021 and parameters: {'n_estimators': 10, 'max_depth': 9, 'min_samples_split': 8}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:11,979] Trial 9 finished with value: 0.8982184980934479 and parameters: {'n_estimators': 146, 'max_depth': 4, 'min_samples_split': 5}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:12,700] Trial 10 finished with value: 0.9035631810707798 and parameters: {'n_estimators': 75, 'max_depth': 32, 'min_samples_split': 2}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:14,658] Trial 11 finished with value: 0.9043444307494408 and parameters: {'n_estimators': 200, 'max_depth': 13, 'min_samples_split': 5}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:15,880] Trial 12 finished with value: 0.9039550636939623 and parameters: {'n_estimators': 120, 'max_depth': 15, 'min_samples_split': 3}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:17,498] Trial 13 finished with value: 0.9039770684257741 and parameters: {'n_estimators': 169, 'max_depth': 14, 'min_samples_split': 6}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:17,718] Trial 14 finished with value: 0.9035106197983598 and parameters: {'n_estimators': 20, 'max_depth': 32, 'min_samples_split': 7}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:18,684] Trial 15 finished with value: 0.9057774073502027 and parameters: {'n_estimators': 97, 'max_depth': 10, 'min_samples_split': 10}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:19,512] Trial 16 finished with value: 0.906988850831705 and parameters: {'n_estimators': 89, 'max_depth': 9, 'min_samples_split': 10}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:19,779] Trial 17 finished with value: 0.889782270865241 and parameters: {'n_estimators': 49, 'max_depth': 4, 'min_samples_split': 9}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:20,108] Trial 18 finished with value: 0.8964638302803852 and parameters: {'n_estimators': 74, 'max_depth': 3, 'min_samples_split': 4}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:20,465] Trial 19 finished with value: 0.9045823347265586 and parameters: {'n_estimators': 34, 'max_depth': 21, 'min_samples_split': 9}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:21,061] Trial 20 finished with value: 0.9045823347265586 and parameters: {'n_estimators': 77, 'max_depth': 7, 'min_samples_split': 10}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:21,938] Trial 21 finished with value: 0.9045823347265586 and parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 10}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:22,920] Trial 22 finished with value: 0.9027436202124601 and parameters: {'n_estimators': 115, 'max_depth': 9, 'min_samples_split': 8}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:23,513] Trial 23 finished with value: 0.9016598883940636 and parameters: {'n_estimators': 91, 'max_depth': 5, 'min_samples_split': 9}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:24,811] Trial 24 finished with value: 0.9057774073502027 and parameters: {'n_estimators': 135, 'max_depth': 10, 'min_samples_split': 10}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:25,451] Trial 25 finished with value: 0.9051885119072762 and parameters: {'n_estimators': 64, 'max_depth': 18, 'min_samples_split': 6}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:26,187] Trial 26 finished with value: 0.9021125360688405 and parameters: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 8}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:27,050] Trial 27 finished with value: 0.9057774073502027 and parameters: {'n_estimators': 90, 'max_depth': 8, 'min_samples_split': 9}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:28,193] Trial 28 finished with value: 0.9057774073502027 and parameters: {'n_estimators': 124, 'max_depth': 12, 'min_samples_split': 10}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:28,367] Trial 29 finished with value: 0.8791251084989226 and parameters: {'n_estimators': 38, 'max_depth': 3, 'min_samples_split': 10}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:29,020] Trial 30 finished with value: 0.902374983587648 and parameters: {'n_estimators': 63, 'max_depth': 26, 'min_samples_split': 4}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:30,310] Trial 31 finished with value: 0.9057774073502027 and parameters: {'n_estimators': 137, 'max_depth': 10, 'min_samples_split': 10}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:31,421] Trial 32 finished with value: 0.9057774073502027 and parameters: {'n_estimators': 133, 'max_depth': 7, 'min_samples_split': 9}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:32,956] Trial 33 finished with value: 0.9057774073502027 and parameters: {'n_estimators': 157, 'max_depth': 17, 'min_samples_split': 10}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:34,018] Trial 34 finished with value: 0.9037641965126071 and parameters: {'n_estimators': 110, 'max_depth': 11, 'min_samples_split': 8}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:34,771] Trial 35 finished with value: 0.903329538305977 and parameters: {'n_estimators': 103, 'max_depth': 6, 'min_samples_split': 9}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:36,308] Trial 36 finished with value: 0.9057774073502027 and parameters: {'n_estimators': 162, 'max_depth': 24, 'min_samples_split': 10}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:37,905] Trial 37 finished with value: 0.9043444307494408 and parameters: {'n_estimators': 175, 'max_depth': 9, 'min_samples_split': 8}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:38,750] Trial 38 finished with value: 0.9031493581257969 and parameters: {'n_estimators': 85, 'max_depth': 19, 'min_samples_split': 9}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:39,170] Trial 39 finished with value: 0.8923152190852353 and parameters: {'n_estimators': 128, 'max_depth': 2, 'min_samples_split': 7}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:40,419] Trial 40 finished with value: 0.9041765968132219 and parameters: {'n_estimators': 142, 'max_depth': 8, 'min_samples_split': 8}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:41,202] Trial 41 finished with value: 0.9057774073502027 and parameters: {'n_estimators': 89, 'max_depth': 8, 'min_samples_split': 9}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:41,683] Trial 42 finished with value: 0.9035633104576121 and parameters: {'n_estimators': 64, 'max_depth': 6, 'min_samples_split': 10}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:42,449] Trial 43 finished with value: 0.9031493581257969 and parameters: {'n_estimators': 82, 'max_depth': 16, 'min_samples_split': 9}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:43,398] Trial 44 finished with value: 0.9057774073502027 and parameters: {'n_estimators': 96, 'max_depth': 12, 'min_samples_split': 10}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:43,853] Trial 45 finished with value: 0.9003032464224517 and parameters: {'n_estimators': 71, 'max_depth': 5, 'min_samples_split': 7}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:44,872] Trial 46 finished with value: 0.9045604051130663 and parameters: {'n_estimators': 109, 'max_depth': 10, 'min_samples_split': 6}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:45,404] Trial 47 finished with value: 0.9031493581257969 and parameters: {'n_estimators': 54, 'max_depth': 13, 'min_samples_split': 9}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:46,391] Trial 48 finished with value: 0.9043444307494408 and parameters: {'n_estimators': 115, 'max_depth': 8, 'min_samples_split': 10}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:47,302] Trial 49 finished with value: 0.9043828063391107 and parameters: {'n_estimators': 94, 'max_depth': 22, 'min_samples_split': 9}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:48,263] Trial 50 finished with value: 0.8971964176174702 and parameters: {'n_estimators': 184, 'max_depth': 4, 'min_samples_split': 2}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:49,530] Trial 51 finished with value: 0.9057774073502027 and parameters: {'n_estimators': 124, 'max_depth': 12, 'min_samples_split': 10}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:51,014] Trial 52 finished with value: 0.9043444307494408 and parameters: {'n_estimators': 152, 'max_depth': 14, 'min_samples_split': 10}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:51,992] Trial 53 finished with value: 0.9057774073502027 and parameters: {'n_estimators': 107, 'max_depth': 10, 'min_samples_split': 10}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:52,680] Trial 54 finished with value: 0.9057774073502027 and parameters: {'n_estimators': 83, 'max_depth': 7, 'min_samples_split': 9}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:53,789] Trial 55 finished with value: 0.9057774073502027 and parameters: {'n_estimators': 121, 'max_depth': 27, 'min_samples_split': 10}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:54,991] Trial 56 finished with value: 0.9027436202124601 and parameters: {'n_estimators': 130, 'max_depth': 9, 'min_samples_split': 8}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:55,663] Trial 57 finished with value: 0.9041070203490392 and parameters: {'n_estimators': 69, 'max_depth': 15, 'min_samples_split': 5}. Best is trial 5 with value: 0.9070108555635166.
[I 2026-04-14 20:30:56,417] Trial 58 finished with value: 0.9073556712599021 and parameters: {'n_estimators': 78, 'max_depth': 11, 'min_samples_split': 10}. Best is trial 58 with value: 0.9073556712599021.
[I 2026-04-14 20:30:57,101] Trial 59 finished with value: 0.9057774073502027 and parameters: {'n_estimators': 78, 'max_depth': 8, 'min_samples_split': 9}. Best is trial 58 with value: 0.9073556712599021.
[I 2026-04-14 20:30:57,442] Trial 60 finished with value: 0.8999080602827505 and parameters: {'n_estimators': 42, 'max_depth': 6, 'min_samples_split': 10}. Best is trial 58 with value: 0.9073556712599021.
[I 2026-04-14 20:30:58,320] Trial 61 finished with value: 0.9057774073502027 and parameters: {'n_estimators': 88, 'max_depth': 10, 'min_samples_split': 10}. Best is trial 58 with value: 0.9073556712599021.
[I 2026-04-14 20:30:59,269] Trial 62 finished with value: 0.9045823347265586 and parameters: {'n_estimators': 96, 'max_depth': 11, 'min_samples_split': 10}. Best is trial 58 with value: 0.9073556712599021.
[I 2026-04-14 20:30:59,845] Trial 63 finished with value: 0.9071912775962877 and parameters: {'n_estimators': 59, 'max_depth': 12, 'min_samples_split': 10}. Best is trial 58 with value: 0.9073556712599021.
[I 2026-04-14 20:31:00,417] Trial 64 finished with value: 0.9018977709681693 and parameters: {'n_estimators': 57, 'max_depth': 9, 'min_samples_split': 9}. Best is trial 58 with value: 0.9073556712599021.
[I 2026-04-14 20:31:00,664] Trial 65 finished with value: 0.9060158290423989 and parameters: {'n_estimators': 24, 'max_depth': 14, 'min_samples_split': 10}. Best is trial 58 with value: 0.9073556712599021.
[I 2026-04-14 20:31:00,818] Trial 66 finished with value: 0.8948492152959654 and parameters: {'n_estimators': 13, 'max_depth': 29, 'min_samples_split': 4}. Best is trial 58 with value: 0.9073556712599021.
[I 2026-04-14 20:31:01,084] Trial 67 finished with value: 0.9032872538246295 and parameters: {'n_estimators': 25, 'max_depth': 14, 'min_samples_split': 10}. Best is trial 58 with value: 0.9073556712599021.
[I 2026-04-14 20:31:01,522] Trial 68 finished with value: 0.9057255699591362 and parameters: {'n_estimators': 46, 'max_depth': 17, 'min_samples_split': 10}. Best is trial 58 with value: 0.9073556712599021.
[I 2026-04-14 20:31:02,115] Trial 69 finished with value: 0.903736039026232 and parameters: {'n_estimators': 60, 'max_depth': 13, 'min_samples_split': 5}. Best is trial 58 with value: 0.9073556712599021.
[I 2026-04-14 20:31:02,426] Trial 70 finished with value: 0.9031493581257969 and parameters: {'n_estimators': 31, 'max_depth': 20, 'min_samples_split': 9}. Best is trial 58 with value: 0.9073556712599021.
[I 2026-04-14 20:31:03,162] Trial 71 finished with value: 0.9045823347265586 and parameters: {'n_estimators': 78, 'max_depth': 12, 'min_samples_split': 10}. Best is trial 58 with value: 0.9073556712599021.
[I 2026-04-14 20:31:03,819] Trial 72 finished with value: 0.9053880402947241 and parameters: {'n_estimators': 68, 'max_depth': 11, 'min_samples_split': 6}. Best is trial 58 with value: 0.9073556712599021.
[I 2026-04-14 20:31:04,732] Trial 73 finished with value: 0.906988850831705 and parameters: {'n_estimators': 101, 'max_depth': 9, 'min_samples_split': 10}. Best is trial 58 with value: 0.9073556712599021.
[I 2026-04-14 20:31:05,608] Trial 74 finished with value: 0.9057774073502027 and parameters: {'n_estimators': 100, 'max_depth': 9, 'min_samples_split': 10}. Best is trial 58 with value: 0.9073556712599021.
[I 2026-04-14 20:31:06,033] Trial 75 finished with value: 0.9069642074578876 and parameters: {'n_estimators': 52, 'max_depth': 7, 'min_samples_split': 3}. Best is trial 58 with value: 0.9073556712599021.
[I 2026-04-14 20:31:06,438] Trial 76 finished with value: 0.9069642074578876 and parameters: {'n_estimators': 49, 'max_depth': 7, 'min_samples_split': 3}. Best is trial 58 with value: 0.9073556712599021.
[I 2026-04-14 20:31:06,878] Trial 77 finished with value: 0.9069642074578876 and parameters: {'n_estimators': 52, 'max_depth': 7, 'min_samples_split': 3}. Best is trial 58 with value: 0.9073556712599021.
[I 2026-04-14 20:31:07,240] Trial 78 finished with value: 0.8979105075235314 and parameters: {'n_estimators': 52, 'max_depth': 5, 'min_samples_split': 3}. Best is trial 58 with value: 0.9073556712599021.
[I 2026-04-14 20:31:07,615] Trial 79 finished with value: 0.9083770109898964 and parameters: {'n_estimators': 44, 'max_depth': 7, 'min_samples_split': 3}. Best is trial 79 with value: 0.9083770109898964.
[I 2026-04-14 20:31:07,992] Trial 80 finished with value: 0.9021125360688405 and parameters: {'n_estimators': 47, 'max_depth': 6, 'min_samples_split': 2}. Best is trial 79 with value: 0.9083770109898964.
[I 2026-04-14 20:31:08,318] Trial 81 finished with value: 0.9056796034537434 and parameters: {'n_estimators': 37, 'max_depth': 7, 'min_samples_split': 3}. Best is trial 79 with value: 0.9083770109898964.
[I 2026-04-14 20:31:08,707] Trial 82 finished with value: 0.9083770109898964 and parameters: {'n_estimators': 44, 'max_depth': 7, 'min_samples_split': 3}. Best is trial 79 with value: 0.9083770109898964.
[I 2026-04-14 20:31:09,050] Trial 83 finished with value: 0.9035883104468706 and parameters: {'n_estimators': 42, 'max_depth': 6, 'min_samples_split': 4}. Best is trial 79 with value: 0.9083770109898964.
[I 2026-04-14 20:31:09,456] Trial 84 finished with value: 0.8991342837473075 and parameters: {'n_estimators': 57, 'max_depth': 5, 'min_samples_split': 3}. Best is trial 79 with value: 0.9083770109898964.
[I 2026-04-14 20:31:10,156] Trial 85 finished with value: 0.905555874230943 and parameters: {'n_estimators': 74, 'max_depth': 8, 'min_samples_split': 2}. Best is trial 79 with value: 0.9083770109898964.
[I 2026-04-14 20:31:10,708] Trial 86 finished with value: 0.9057360544111234 and parameters: {'n_estimators': 64, 'max_depth': 7, 'min_samples_split': 3}. Best is trial 79 with value: 0.9083770109898964.
[I 2026-04-14 20:31:10,879] Trial 87 finished with value: 0.8847295466504453 and parameters: {'n_estimators': 31, 'max_depth': 3, 'min_samples_split': 4}. Best is trial 79 with value: 0.9083770109898964.
[I 2026-04-14 20:31:11,252] Trial 88 finished with value: 0.8957771385959304 and parameters: {'n_estimators': 45, 'max_depth': 6, 'min_samples_split': 3}. Best is trial 79 with value: 0.9083770109898964.
[I 2026-04-14 20:31:11,863] Trial 89 finished with value: 0.9028919578683965 and parameters: {'n_estimators': 61, 'max_depth': 8, 'min_samples_split': 2}. Best is trial 79 with value: 0.9083770109898964.
[I 2026-04-14 20:31:12,224] Trial 90 finished with value: 0.8983030174960343 and parameters: {'n_estimators': 67, 'max_depth': 4, 'min_samples_split': 4}. Best is trial 79 with value: 0.9083770109898964.
[I 2026-04-14 20:31:12,664] Trial 91 finished with value: 0.9039550636939623 and parameters: {'n_estimators': 49, 'max_depth': 9, 'min_samples_split': 3}. Best is trial 79 with value: 0.9083770109898964.
[I 2026-04-14 20:31:13,071] Trial 92 finished with value: 0.9082170038784693 and parameters: {'n_estimators': 54, 'max_depth': 7, 'min_samples_split': 3}. Best is trial 79 with value: 0.9083770109898964.
[I 2026-04-14 20:31:13,526] Trial 93 finished with value: 0.9082170038784693 and parameters: {'n_estimators': 57, 'max_depth': 7, 'min_samples_split': 3}. Best is trial 79 with value: 0.9083770109898964.
[I 2026-04-14 20:31:13,901] Trial 94 finished with value: 0.9057774073502027 and parameters: {'n_estimators': 40, 'max_depth': 8, 'min_samples_split': 3}. Best is trial 79 with value: 0.9083770109898964.
[I 2026-04-14 20:31:14,588] Trial 95 finished with value: 0.9057774073502027 and parameters: {'n_estimators': 81, 'max_depth': 7, 'min_samples_split': 2}. Best is trial 79 with value: 0.9083770109898964.
[I 2026-04-14 20:31:15,105] Trial 96 finished with value: 0.9021644494872147 and parameters: {'n_estimators': 73, 'max_depth': 6, 'min_samples_split': 4}. Best is trial 79 with value: 0.9083770109898964.

,number,value,datetime_start,datetime_complete,duration,params_max_depth,params_min_samples_split,params_n_estimators,state
82,82,0.908377,2026-04-14 20:31:08.318077,2026-04-14 20:31:08.707907,0 days 00:00:00.389830,7,3,44,COMPLETE
79,79,0.908377,2026-04-14 20:31:07.241587,2026-04-14 20:31:07.615085,0 days 00:00:00.373498,7,3,44,COMPLETE
92,92,0.908217,2026-04-14 20:31:12.664470,2026-04-14 20:31:13.071397,0 days 00:00:00.406927,7,3,54,COMPLETE
93,93,0.908217,2026-04-14 20:31:13.071397,2026-04-14 20:31:13.526399,0 days 00:00:00.455002,7,3,57,COMPLETE
58,58,0.907356,2026-04-14 20:30:55.663834,2026-04-14 20:30:56.417245,0 days 00:00:00.753411,11,10,78,COMPLETE

In [26]:
# Train using optimal parameters
model_2 = RandomForestClassifier(
    class_weight='balanced',
    n_estimators=top_5_f1_df.head(1)['params_n_estimators'].item(),
    max_depth=top_5_f1_df.head(1)['params_max_depth'].item(),
    min_samples_split=top_5_f1_df.head(1)['params_min_samples_split'].item(),
    random_state=random_state
)
model_2.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', max_depth=7,
                       min_samples_split=3, n_estimators=44, random_state=42)

In [27]:
y_pred = model_2.predict(X_test)

In [28]:
print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       985
           1       0.98      0.90      0.94        98

    accuracy                           0.99      1083
   macro avg       0.98      0.95      0.97      1083
weighted avg       0.99      0.99      0.99      1083

In [29]:
f1_model_report_df = classification_report(y_test, y_pred, output_dict=True)

### Analyze reports

In [38]:
# 2. Convert and transpose
recall_report_df = pd.DataFrame(recall_model_report_df).transpose()
f1_report_df = pd.DataFrame(f1_model_report_df).transpose()

# 3. Combine multiple reports (e.g., adding a 'Model' column for identification)
combined_df = pd.concat([recall_report_df, f1_report_df], keys=['CC RF optimized for Recall', 'CC RF optimized for F1'])

In [39]:
combined_df

                                         precision    recall  f1-score  \
CC RF optimized for Recall 0              0.990891  0.993909  0.992397
                           1              0.936842  0.908163  0.922280
                           accuracy       0.986150  0.986150  0.986150
                           macro avg      0.963866  0.951036  0.957339
                           weighted avg   0.986000  0.986150  0.986052
CC RF optimized for F1     0              0.989930  0.997970  0.993933
                           1              0.977778  0.897959  0.936170
                           accuracy       0.988920  0.988920  0.988920
                           macro avg      0.983854  0.947964  0.965052
                           weighted avg   0.988830  0.988920  0.988706

                                            support
CC RF optimized for Recall 0              985.00000
                           1               98.00000
                           accuracy         0.98615
                           macro avg     1083.00000
                           weighted avg  1083.00000
CC RF optimized for F1     0              985.00000
                           1               98.00000
                           accuracy         0.98892
                           macro avg     1083.00000
                           weighted avg  1083.00000

In [32]:
# Recall model
importances = model_1.feature_importances_
feature_names = df.drop(columns='Class').columns
feature_imp_recall_df = pd.DataFrame({'Feature': feature_names, 'Gini Importance': importances}).sort_values(
    'Gini Importance', ascending=False)
feature_imp_recall_df

   Feature  Gini Importance
14     V14         0.308357
10     V10         0.136394
17     V17         0.099583
4       V4         0.095286
3       V3         0.077117
16     V16         0.076696
12     V12         0.075937
2       V2         0.022241
9       V9         0.019767
7       V7         0.015803
11     V11         0.013373
21     V21         0.011931
19     V19         0.010226
27     V27         0.009983
18     V18         0.004817
29  Amount         0.004341
20     V20         0.004051
23     V23         0.002240
13     V13         0.002192
6       V6         0.001619
8       V8         0.001511
28     V28         0.001321
1       V1         0.001238
15     V15         0.001233
5       V5         0.001013
25     V25         0.000702
22     V22         0.000482
24     V24         0.000381
26     V26         0.000165
0     Time         0.000000

In [33]:
# Recall model
importances = model_2.feature_importances_
feature_names = df.drop(columns='Class').columns
feature_imp_f1_df = pd.DataFrame({'Feature': feature_names, 'Gini Importance': importances}).sort_values(
    'Gini Importance', ascending=False)
feature_imp_f1_df

   Feature  Gini Importance
14     V14         0.262059
4       V4         0.106912
10     V10         0.093380
17     V17         0.091772
12     V12         0.086796
16     V16         0.076890
3       V3         0.075675
2       V2         0.025106
7       V7         0.022226
9       V9         0.020086
11     V11         0.013846
21     V21         0.013592
27     V27         0.010526
19     V19         0.010383
20     V20         0.009215
8       V8         0.008587
18     V18         0.008199
29  Amount         0.008184
5       V5         0.008098
23     V23         0.006473
13     V13         0.005936
6       V6         0.005406
1       V1         0.005280
15     V15         0.004660
28     V28         0.004592
22     V22         0.004541
0     Time         0.003591
24     V24         0.003043
26     V26         0.002775
25     V25         0.002170