In [ ]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import root_mean_squared_error
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import make_scorer
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import RepeatedKFold
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report

In [ ]:
df = pd.read_csv('Milestone 3 EDA/ibm_hi_small_trans_cleaned.csv')
df

,Timestamp,From Bank,Account,To Bank,Account.1,Amount Received,Amount Paid,Is Laundering,Amount_Received_USD,Amount_Paid_USD,...,Payment Currency_Yuan,Payment Format_ACH,Payment Format_Bitcoin,Payment Format_Cash,Payment Format_Cheque,Payment Format_Credit Card,Payment Format_Reinvestment,Payment Format_Wire,Account_Same,Bank_Same
0,2022/09/01 00:20,10,8000EBD30,10,8000EBD30,3697.340000,3697.340000,0,3697.340000,3697.340000,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,1
1,2022/09/01 00:20,3208,8000F4580,1,8000F5340,0.010000,0.010000,0,0.010000,0.010000,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0,0
2,2022/09/01 00:00,3209,8000F4670,3209,8000F4670,14675.570000,14675.570000,0,14675.570000,14675.570000,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,1
3,2022/09/01 00:02,12,8000F5030,12,8000F5030,2806.970000,2806.970000,0,2806.970000,2806.970000,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,1
4,2022/09/01 00:06,10,8000F5200,10,8000F5200,36682.970000,36682.970000,0,36682.970000,36682.970000,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5078340,2022/09/10 23:57,54219,8148A6631,256398,8148A8711,0.154978,0.154978,0,3107.386389,3107.386389,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0
5078341,2022/09/10 23:35,15,8148A8671,256398,8148A8711,0.108128,0.108128,0,2168.020464,2168.020464,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0
5078342,2022/09/10 23:52,154365,8148A6771,256398,8148A8711,0.004988,0.004988,0,100.011894,100.011894,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0
5078343,2022/09/10 23:46,256398,8148A6311,256398,8148A8711,0.038417,0.038417,0,770.280058,770.280058,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,1
5078344,2022/09/10 23:37,154518,8148A6091,256398,8148A8711,0.281983,0.281983,0,5653.900141,5653.900141,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0

In [ ]:
df.columns

Index(['Timestamp', 'From Bank', 'Account', 'To Bank', 'Account.1',
       'Amount Received', 'Amount Paid', 'Is Laundering',
       'Amount_Received_USD', 'Amount_Paid_USD',
       ...
       'Payment Currency_Yuan', 'Payment Format_ACH', 'Payment Format_Bitcoin',
       'Payment Format_Cash', 'Payment Format_Cheque',
       'Payment Format_Credit Card', 'Payment Format_Reinvestment',
       'Payment Format_Wire', 'Account_Same', 'Bank_Same'],
      dtype='object', length=109)

In [ ]:
df.drop(columns=['Timestamp', 'From Bank', 'To Bank', 'Account', 'Account.1'], inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5078345 entries, 0 to 5078344
Columns: 104 entries, Amount Received to Bank_Same
dtypes: float64(101), int64(3)
memory usage: 3.9 GB

In [ ]:
random_state = 42

In [ ]:
fraud = df[df['Is Laundering'] == 1]
non_fraud = df[df['Is Laundering'] == 0]
len(fraud), len(non_fraud)

(5177, 5073168)

In [ ]:
# Undersample majority class to a 1:10 ratio
non_fraud_downsampled = non_fraud.sample(n=len(fraud) * 10, random_state=random_state)
non_fraud_downsampled

,Amount Received,Amount Paid,Is Laundering,Amount_Received_USD,Amount_Paid_USD,US Dollar_Amount_Paid_Mean,US Dollar_Amount_Paid_Median,US Dollar_Amount_Received_Mean,US Dollar_Amount_Received_Median,Bitcoin_Amount_Paid_Mean,...,Payment Currency_Yuan,Payment Format_ACH,Payment Format_Bitcoin,Payment Format_Cash,Payment Format_Cheque,Payment Format_Credit Card,Payment Format_Reinvestment,Payment Format_Wire,Account_Same,Bank_Same
4563287,1439.79,1439.79,0,3.829841e+02,3.829841e+02,367153.780541,904.13,4.041979e+06,908.2,20.809275,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0,0
4216770,33.09,33.09,0,3.309000e+01,3.309000e+01,367153.780541,904.13,4.041979e+06,908.2,20.809275,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0,0
2992877,263.34,263.34,0,3.807896e+01,3.807896e+01,367153.780541,904.13,4.041979e+06,908.2,20.809275,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
1499016,17154983.76,17154983.76,0,1.747064e+07,1.747064e+07,367153.780541,904.13,4.041979e+06,908.2,20.809275,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0,0
510282,8499.22,8499.22,0,2.501320e+03,2.501320e+03,367153.780541,904.13,4.041979e+06,908.2,20.809275,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3992741,5722.87,5722.87,0,5.722870e+03,5.722870e+03,367153.780541,904.13,4.041979e+06,908.2,20.809275,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0,0
44465,82208.92,82208.92,0,8.220892e+04,8.220892e+04,367153.780541,904.13,4.041979e+06,908.2,20.809275,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0,0
1173046,6837.09,6837.09,0,5.196872e+03,5.196872e+03,367153.780541,904.13,4.041979e+06,908.2,20.809275,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0,0
4125810,3261.27,3261.27,0,3.763506e+03,3.763506e+03,367153.780541,904.13,4.041979e+06,908.2,20.809275,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0,0
3821365,20287.92,20287.92,0,2.933633e+03,2.933633e+03,367153.780541,904.13,4.041979e+06,908.2,20.809275,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0

In [ ]:
# Combine and shuffle
df_reduced = pd.concat([fraud, non_fraud_downsampled]).sample(frac=1).reset_index(drop=True)
df_reduced

,Amount Received,Amount Paid,Is Laundering,Amount_Received_USD,Amount_Paid_USD,US Dollar_Amount_Paid_Mean,US Dollar_Amount_Paid_Median,US Dollar_Amount_Received_Mean,US Dollar_Amount_Received_Median,Bitcoin_Amount_Paid_Mean,...,Payment Currency_Yuan,Payment Format_ACH,Payment Format_Bitcoin,Payment Format_Cash,Payment Format_Cheque,Payment Format_Credit Card,Payment Format_Reinvestment,Payment Format_Wire,Account_Same,Bank_Same
0,142.21,142.21,0,141.427845,141.427845,367153.780541,904.13,4.041979e+06,908.2,20.809275,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0,0
1,8.12,8.12,0,8.269408,8.269408,367153.780541,904.13,4.041979e+06,908.2,20.809275,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,1
2,234.56,234.56,0,233.269920,233.269920,367153.780541,904.13,4.041979e+06,908.2,20.809275,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0,0
3,19640.00,19640.00,0,20001.376000,20001.376000,367153.780541,904.13,4.041979e+06,908.2,20.809275,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0,0
4,8.38,8.38,0,8.380000,8.380000,367153.780541,904.13,4.041979e+06,908.2,20.809275,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56942,78922.59,78922.59,0,3906.668205,3906.668205,367153.780541,904.13,4.041979e+06,908.2,20.809275,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0,0
56943,89535.13,89535.13,0,635.699423,635.699423,367153.780541,904.13,4.041979e+06,908.2,20.809275,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0,0
56944,207870.51,207870.51,0,2598.381375,2598.381375,367153.780541,904.13,4.041979e+06,908.2,20.809275,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0,0
56945,29.48,29.48,0,29.317860,29.317860,367153.780541,904.13,4.041979e+06,908.2,20.809275,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0,0
56946,208.99,208.99,0,30.219954,30.219954,367153.780541,904.13,4.041979e+06,908.2,20.809275,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0,0

In [ ]:
X = df_reduced.drop(columns='Is Laundering')
y = df_reduced['Is Laundering']

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    test_size=0.2, 
                                                    stratify=y,  # Maintains class distribution
                                                    random_state=random_state
                                                    )

In [ ]:
scaler = StandardScaler()

In [ ]:
X_train_scaled = scaler.fit_transform(X_train)
X_train_scaled

array([[-0.01368816, -0.01278547, -0.01008913, ..., -0.18157169,
        -0.34846905, -0.38402302],
       [-0.01368897, -0.01278628, -0.01009458, ..., -0.18157169,
        -0.34846905, -0.38402302],
       [-0.01368909, -0.0127864 , -0.01009542, ..., -0.18157169,
        -0.34846905, -0.38402302],
       ...,
       [-0.01368367, -0.01278097, -0.01005863, ..., -0.18157169,
        -0.34846905, -0.38402302],
       [-0.01253343, -0.01162778, -0.01003977, ..., -0.18157169,
        -0.34846905, -0.38402302],
       [-0.01368867, -0.01278597, -0.01009256, ..., -0.18157169,
        -0.34846905, -0.38402302]], shape=(45557, 103))

In [ ]:
X_test_scaled = scaler.transform(X_test)

In [ ]:
# cv = RepeatedKFold(n_splits=5, n_repeats=5, random_state=random_state)
from sklearn.model_selection import StratifiedKFold


cv = StratifiedKFold(n_splits=5)

### RF with scaled data & recall as param tuning metric

In [ ]:
# Parameter tuning
import optuna
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score


def objective(trial):
    n_estimators = trial.suggest_int("n_estimators", 10, 200)
    max_depth = trial.suggest_int("max_depth", 2, 32, log=True)
    min_samples_split = trial.suggest_int("min_samples_split", 2, 10)
    
    model = RandomForestClassifier(
        class_weight='balanced',
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        random_state=random_state
    )
    
    scores = cross_val_score(
        model, 
        X=X_train_scaled, 
        y=y_train, 
        cv=cv,
        # scoring="f1",
        scoring='recall',
        n_jobs=-1,
    )
    # f1 = scores.mean()
    recall = scores.mean()
    
    # return f1
    return recall


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

top_5_df = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_df)

c:\Users\caleb\anaconda3\envs\iris-fisher\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
[I 2026-04-14 14:20:48,392] A new study created in memory with name: no-name-65efc86f-277b-40e7-beb9-528fedfb91a3
[I 2026-04-14 14:20:54,968] Trial 0 finished with value: 0.7083527094514664 and parameters: {'n_estimators': 144, 'max_depth': 28, 'min_samples_split': 4}. Best is trial 0 with value: 0.7083527094514664.
[I 2026-04-14 14:21:00,310] Trial 1 finished with value: 0.7706456180836 and parameters: {'n_estimators': 148, 'max_depth': 25, 'min_samples_split': 7}. Best is trial 1 with value: 0.7706456180836.
[I 2026-04-14 14:21:02,198] Trial 2 finished with value: 0.8063766367720844 and parameters: {'n_estimators': 116, 'max_depth': 2, 'min_samples_split': 7}. Best is trial 2 with value: 0.8063766367720844.
[I 2026-04-14 14:21:05,192] Trial 3 finished with value: 0.826893760598591 and parameters: {'n_estimators': 171, 'max_depth': 4, 'min_samples_split': 5}. Best is trial 3 with value: 0.826893760598591.
[I 2026-04-14 14:21:06,681] Trial 4 finished with value: 0.8319647675157194 and parameters: {'n_estimators': 97, 'max_depth': 5, 'min_samples_split': 6}. Best is trial 4 with value: 0.8319647675157194.
[I 2026-04-14 14:21:07,977] Trial 5 finished with value: 0.8322042738180567 and parameters: {'n_estimators': 74, 'max_depth': 6, 'min_samples_split': 8}. Best is trial 5 with value: 0.8322042738180567.
[I 2026-04-14 14:21:10,086] Trial 6 finished with value: 0.7887534017470557 and parameters: {'n_estimators': 68, 'max_depth': 23, 'min_samples_split': 8}. Best is trial 5 with value: 0.8322042738180567.
[I 2026-04-14 14:21:12,063] Trial 7 finished with value: 0.8090321847520148 and parameters: {'n_estimators': 191, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 5 with value: 0.8322042738180567.
[I 2026-04-14 14:21:16,910] Trial 8 finished with value: 0.8174830859600357 and parameters: {'n_estimators': 191, 'max_depth': 17, 'min_samples_split': 8}. Best is trial 5 with value: 0.8322042738180567.
[I 2026-04-14 14:21:18,061] Trial 9 finished with value: 0.8051689073034854 and parameters: {'n_estimators': 125, 'max_depth': 2, 'min_samples_split': 2}. Best is trial 5 with value: 0.8322042738180567.
[I 2026-04-14 14:21:18,729] Trial 10 finished with value: 0.8389678502124088 and parameters: {'n_estimators': 25, 'max_depth': 10, 'min_samples_split': 10}. Best is trial 10 with value: 0.8389678502124088.
[I 2026-04-14 14:21:19,210] Trial 11 finished with value: 0.8244812153633678 and parameters: {'n_estimators': 10, 'max_depth': 9, 'min_samples_split': 10}. Best is trial 10 with value: 0.8389678502124088.
[I 2026-04-14 14:21:20,002] Trial 12 finished with value: 0.8447637861808943 and parameters: {'n_estimators': 31, 'max_depth': 10, 'min_samples_split': 10}. Best is trial 12 with value: 0.8447637861808943.
[I 2026-04-14 14:21:20,453] Trial 13 finished with value: 0.8360701735983638 and parameters: {'n_estimators': 13, 'max_depth': 11, 'min_samples_split': 10}. Best is trial 12 with value: 0.8447637861808943.
[I 2026-04-14 14:21:21,749] Trial 14 finished with value: 0.8382461262332243 and parameters: {'n_estimators': 50, 'max_depth': 13, 'min_samples_split': 10}. Best is trial 12 with value: 0.8447637861808943.
[I 2026-04-14 14:21:22,608] Trial 15 finished with value: 0.8404165428343328 and parameters: {'n_estimators': 39, 'max_depth': 8, 'min_samples_split': 9}. Best is trial 12 with value: 0.8447637861808943.
[I 2026-04-14 14:21:23,497] Trial 16 finished with value: 0.8338959691846879 and parameters: {'n_estimators': 43, 'max_depth': 7, 'min_samples_split': 9}. Best is trial 12 with value: 0.8447637861808943.
[I 2026-04-14 14:21:25,784] Trial 17 finished with value: 0.825932530317069 and parameters: {'n_estimators': 87, 'max_depth': 16, 'min_samples_split': 9}. Best is trial 12 with value: 0.8447637861808943.
[I 2026-04-14 14:21:26,705] Trial 18 finished with value: 0.8401752883108105 and parameters: {'n_estimators': 44, 'max_depth': 8, 'min_samples_split': 9}. Best is trial 12 with value: 0.8447637861808943.
[I 2026-04-14 14:21:27,328] Trial 19 finished with value: 0.8027549052172749 and parameters: {'n_estimators': 36, 'max_depth': 4, 'min_samples_split': 7}. Best is trial 12 with value: 0.8447637861808943.
[I 2026-04-14 14:21:29,138] Trial 20 finished with value: 0.8235182368606611 and parameters: {'n_estimators': 69, 'max_depth': 15, 'min_samples_split': 3}. Best is trial 12 with value: 0.8447637861808943.
[I 2026-04-14 14:21:30,275] Trial 21 finished with value: 0.8474196255310222 and parameters: {'n_estimators': 56, 'max_depth': 8, 'min_samples_split': 9}. Best is trial 21 with value: 0.8474196255310222.
[I 2026-04-14 14:21:31,353] Trial 22 finished with value: 0.8252049789339347 and parameters: {'n_estimators': 60, 'max_depth': 6, 'min_samples_split': 9}. Best is trial 21 with value: 0.8474196255310222.
[I 2026-04-14 14:21:31,929] Trial 23 finished with value: 0.8372808167689374 and parameters: {'n_estimators': 20, 'max_depth': 11, 'min_samples_split': 8}. Best is trial 21 with value: 0.8474196255310222.
[I 2026-04-14 14:21:32,661] Trial 24 finished with value: 0.8450044579640215 and parameters: {'n_estimators': 31, 'max_depth': 8, 'min_samples_split': 9}. Best is trial 21 with value: 0.8474196255310222.
[I 2026-04-14 14:21:33,613] Trial 25 finished with value: 0.8049267786693706 and parameters: {'n_estimators': 28, 'max_depth': 20, 'min_samples_split': 10}. Best is trial 21 with value: 0.8474196255310222.
[I 2026-04-14 14:21:34,501] Trial 26 finished with value: 0.8073419462363711 and parameters: {'n_estimators': 54, 'max_depth': 5, 'min_samples_split': 8}. Best is trial 21 with value: 0.8474196255310222.
[I 2026-04-14 14:21:36,417] Trial 27 finished with value: 0.836315507304651 and parameters: {'n_estimators': 79, 'max_depth': 13, 'min_samples_split': 6}. Best is trial 21 with value: 0.8474196255310222.
[I 2026-04-14 14:21:37,492] Trial 28 finished with value: 0.8056517077207275 and parameters: {'n_estimators': 92, 'max_depth': 3, 'min_samples_split': 9}. Best is trial 21 with value: 0.8474196255310222.
[I 2026-04-14 14:21:38,121] Trial 29 finished with value: 0.8153103383973473 and parameters: {'n_estimators': 30, 'max_depth': 6, 'min_samples_split': 7}. Best is trial 21 with value: 0.8474196255310222.
[I 2026-04-14 14:21:39,996] Trial 30 finished with value: 0.7643683385488599 and parameters: {'n_estimators': 59, 'max_depth': 31, 'min_samples_split': 10}. Best is trial 21 with value: 0.8474196255310222.
[I 2026-04-14 14:21:40,916] Trial 31 finished with value: 0.8380010838971346 and parameters: {'n_estimators': 42, 'max_depth': 8, 'min_samples_split': 9}. Best is trial 21 with value: 0.8474196255310222.
[I 2026-04-14 14:21:41,662] Trial 32 finished with value: 0.8464543160667354 and parameters: {'n_estimators': 29, 'max_depth': 9, 'min_samples_split': 9}. Best is trial 21 with value: 0.8474196255310222.
[I 2026-04-14 14:21:42,383] Trial 33 finished with value: 0.8392105615869185 and parameters: {'n_estimators': 20, 'max_depth': 12, 'min_samples_split': 7}. Best is trial 21 with value: 0.8474196255310222.
[I 2026-04-14 14:21:45,758] Trial 34 finished with value: 0.8508001025623095 and parameters: {'n_estimators': 139, 'max_depth': 9, 'min_samples_split': 8}. Best is trial 34 with value: 0.8508001025623095.
[I 2026-04-14 14:21:48,785] Trial 35 finished with value: 0.8479021345780667 and parameters: {'n_estimators': 143, 'max_depth': 7, 'min_samples_split': 8}. Best is trial 34 with value: 0.8508001025623095.
[I 2026-04-14 14:21:51,105] Trial 36 finished with value: 0.8367942285391281 and parameters: {'n_estimators': 150, 'max_depth': 5, 'min_samples_split': 8}. Best is trial 34 with value: 0.8508001025623095.
[I 2026-04-14 14:21:52,788] Trial 37 finished with value: 0.8145819129036207 and parameters: {'n_estimators': 135, 'max_depth': 4, 'min_samples_split': 5}. Best is trial 34 with value: 0.8508001025623095.
[I 2026-04-14 14:21:54,486] Trial 38 finished with value: 0.8396927792637658 and parameters: {'n_estimators': 107, 'max_depth': 6, 'min_samples_split': 6}. Best is trial 34 with value: 0.8508001025623095.
[I 2026-04-14 14:21:57,157] Trial 39 finished with value: 0.8491095726764684 and parameters: {'n_estimators': 165, 'max_depth': 7, 'min_samples_split': 7}. Best is trial 34 with value: 0.8508001025623095.
[I 2026-04-14 14:21:58,896] Trial 40 finished with value: 0.8071009830830465 and parameters: {'n_estimators': 163, 'max_depth': 3, 'min_samples_split': 7}. Best is trial 34 with value: 0.8508001025623095.
[I 2026-04-14 14:22:02,027] Trial 41 finished with value: 0.8483852263655065 and parameters: {'n_estimators': 169, 'max_depth': 7, 'min_samples_split': 8}. Best is trial 34 with value: 0.8508001025623095.
[I 2026-04-14 14:22:04,876] Trial 42 finished with value: 0.8479027173184617 and parameters: {'n_estimators': 175, 'max_depth': 7, 'min_samples_split': 8}. Best is trial 34 with value: 0.8508001025623095.
[I 2026-04-14 14:22:07,639] Trial 43 finished with value: 0.8488683181529459 and parameters: {'n_estimators': 171, 'max_depth': 7, 'min_samples_split': 7}. Best is trial 34 with value: 0.8508001025623095.
[I 2026-04-14 14:22:10,072] Trial 44 finished with value: 0.8384844670547718 and parameters: {'n_estimators': 178, 'max_depth': 5, 'min_samples_split': 6}. Best is trial 34 with value: 0.8508001025623095.
[I 2026-04-14 14:22:13,148] Trial 45 finished with value: 0.8437978939762125 and parameters: {'n_estimators': 200, 'max_depth': 6, 'min_samples_split': 7}. Best is trial 34 with value: 0.8508001025623095.
[I 2026-04-14 14:22:16,427] Trial 46 finished with value: 0.849109864046666 and parameters: {'n_estimators': 163, 'max_depth': 10, 'min_samples_split': 6}. Best is trial 34 with value: 0.8508001025623095.
[I 2026-04-14 14:22:19,618] Trial 47 finished with value: 0.8483852263655065 and parameters: {'n_estimators': 161, 'max_depth': 10, 'min_samples_split': 5}. Best is trial 34 with value: 0.8508001025623095.
[I 2026-04-14 14:22:24,028] Trial 48 finished with value: 0.829555135982471 and parameters: {'n_estimators': 185, 'max_depth': 14, 'min_samples_split': 4}. Best is trial 34 with value: 0.8508001025623095.
[I 2026-04-14 14:22:27,420] Trial 49 finished with value: 0.8479027173184617 and parameters: {'n_estimators': 159, 'max_depth': 11, 'min_samples_split': 6}. Best is trial 34 with value: 0.8508001025623095.
[I 2026-04-14 14:22:29,928] Trial 50 finished with value: 0.8508001025623095 and parameters: {'n_estimators': 130, 'max_depth': 9, 'min_samples_split': 7}. Best is trial 34 with value: 0.8508001025623095.
[I 2026-04-14 14:22:32,368] Trial 51 finished with value: 0.8512831943497492 and parameters: {'n_estimators': 124, 'max_depth': 9, 'min_samples_split': 7}. Best is trial 51 with value: 0.8512831943497492.
[I 2026-04-14 14:22:34,773] Trial 52 finished with value: 0.8512831943497492 and parameters: {'n_estimators': 124, 'max_depth': 9, 'min_samples_split': 7}. Best is trial 51 with value: 0.8512831943497492.
[I 2026-04-14 14:22:37,142] Trial 53 finished with value: 0.8520066665501187 and parameters: {'n_estimators': 122, 'max_depth': 9, 'min_samples_split': 6}. Best is trial 53 with value: 0.8520066665501187.
[I 2026-04-14 14:22:39,526] Trial 54 finished with value: 0.8512820288689593 and parameters: {'n_estimators': 123, 'max_depth': 9, 'min_samples_split': 6}. Best is trial 53 with value: 0.8520066665501187.
[I 2026-04-14 14:22:41,884] Trial 55 finished with value: 0.8515238661328766 and parameters: {'n_estimators': 121, 'max_depth': 9, 'min_samples_split': 6}. Best is trial 53 with value: 0.8520066665501187.
[I 2026-04-14 14:22:44,878] Trial 56 finished with value: 0.8102402055908113 and parameters: {'n_estimators': 109, 'max_depth': 18, 'min_samples_split': 6}. Best is trial 53 with value: 0.8520066665501187.
[I 2026-04-14 14:22:47,516] Trial 57 finished with value: 0.8421091123115563 and parameters: {'n_estimators': 119, 'max_depth': 12, 'min_samples_split': 5}. Best is trial 53 with value: 0.8520066665501187.
[I 2026-04-14 14:22:49,818] Trial 58 finished with value: 0.8512820288689593 and parameters: {'n_estimators': 119, 'max_depth': 9, 'min_samples_split': 6}. Best is trial 53 with value: 0.8520066665501187.
[I 2026-04-14 14:22:52,442] Trial 59 finished with value: 0.8466958619604552 and parameters: {'n_estimators': 123, 'max_depth': 11, 'min_samples_split': 5}. Best is trial 53 with value: 0.8520066665501187.
[I 2026-04-14 14:22:54,886] Trial 60 finished with value: 0.8305207368169555 and parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 4}. Best is trial 53 with value: 0.8520066665501187.
[I 2026-04-14 14:22:57,091] Trial 61 finished with value: 0.8500754648811502 and parameters: {'n_estimators': 114, 'max_depth': 9, 'min_samples_split': 6}. Best is trial 53 with value: 0.8520066665501187.
[I 2026-04-14 14:22:59,663] Trial 62 finished with value: 0.849592081723513 and parameters: {'n_estimators': 137, 'max_depth': 9, 'min_samples_split': 6}. Best is trial 53 with value: 0.8520066665501187.
[I 2026-04-14 14:23:02,316] Trial 63 finished with value: 0.848384934995309 and parameters: {'n_estimators': 128, 'max_depth': 10, 'min_samples_split': 5}. Best is trial 53 with value: 0.8520066665501187.
[I 2026-04-14 14:23:04,953] Trial 64 finished with value: 0.8493511185701882 and parameters: {'n_estimators': 152, 'max_depth': 8, 'min_samples_split': 7}. Best is trial 53 with value: 0.8520066665501187.
[I 2026-04-14 14:23:07,478] Trial 65 finished with value: 0.843076169997028 and parameters: {'n_estimators': 115, 'max_depth': 12, 'min_samples_split': 6}. Best is trial 53 with value: 0.8520066665501187.
[I 2026-04-14 14:23:10,504] Trial 66 finished with value: 0.849592081723513 and parameters: {'n_estimators': 137, 'max_depth': 9, 'min_samples_split': 6}. Best is trial 53 with value: 0.8520066665501187.
[I 2026-04-14 14:23:12,836] Trial 67 finished with value: 0.8500754648811502 and parameters: {'n_estimators': 99, 'max_depth': 8, 'min_samples_split': 5}. Best is trial 53 with value: 0.8520066665501187.
[I 2026-04-14 14:23:15,744] Trial 68 finished with value: 0.8491101554168633 and parameters: {'n_estimators': 122, 'max_depth': 10, 'min_samples_split': 7}. Best is trial 53 with value: 0.8520066665501187.
[I 2026-04-14 14:23:19,677] Trial 69 finished with value: 0.8384879634971417 and parameters: {'n_estimators': 144, 'max_depth': 13, 'min_samples_split': 7}. Best is trial 53 with value: 0.8520066665501187.
[I 2026-04-14 14:23:22,175] Trial 70 finished with value: 0.8389678502124089 and parameters: {'n_estimators': 132, 'max_depth': 6, 'min_samples_split': 6}. Best is trial 53 with value: 0.8520066665501187.
[I 2026-04-14 14:23:25,485] Trial 71 finished with value: 0.8508001025623095 and parameters: {'n_estimators': 131, 'max_depth': 9, 'min_samples_split': 7}. Best is trial 53 with value: 0.8520066665501187.
[I 2026-04-14 14:23:27,923] Trial 72 finished with value: 0.8488680267827485 and parameters: {'n_estimators': 110, 'max_depth': 8, 'min_samples_split': 8}. Best is trial 53 with value: 0.8520066665501187.
[I 2026-04-14 14:23:31,004] Trial 73 finished with value: 0.85031701077487 and parameters: {'n_estimators': 126, 'max_depth': 9, 'min_samples_split': 7}. Best is trial 53 with value: 0.8520066665501187.
[I 2026-04-14 14:23:34,817] Trial 74 finished with value: 0.8466955705902578 and parameters: {'n_estimators': 140, 'max_depth': 11, 'min_samples_split': 5}. Best is trial 53 with value: 0.8520066665501187.
[I 2026-04-14 14:23:36,111] Trial 75 finished with value: 0.8051689073034854 and parameters: {'n_estimators': 118, 'max_depth': 2, 'min_samples_split': 7}. Best is trial 53 with value: 0.8520066665501187.
[I 2026-04-14 14:23:38,598] Trial 76 finished with value: 0.8493508271999908 and parameters: {'n_estimators': 104, 'max_depth': 8, 'min_samples_split': 6}. Best is trial 53 with value: 0.8520066665501187.
[I 2026-04-14 14:23:42,519] Trial 77 finished with value: 0.8476605886843471 and parameters: {'n_estimators': 155, 'max_depth': 10, 'min_samples_split': 2}. Best is trial 53 with value: 0.8520066665501187.
[I 2026-04-14 14:23:45,049] Trial 78 finished with value: 0.846455772917723 and parameters: {'n_estimators': 93, 'max_depth': 12, 'min_samples_split': 8}. Best is trial 53 with value: 0.8520066665501187.
[I 2026-04-14 14:23:47,642] Trial 79 finished with value: 0.8481433891015892 and parameters: {'n_estimators': 129, 'max_depth': 7, 'min_samples_split': 7}. Best is trial 53 with value: 0.8520066665501187.
[I 2026-04-14 14:23:52,012] Trial 80 finished with value: 0.8271408425260631 and parameters: {'n_estimators': 146, 'max_depth': 15, 'min_samples_split': 6}. Best is trial 53 with value: 0.8520066665501187.
[I 2026-04-14 14:23:55,058] Trial 81 finished with value: 0.8500754648811502 and parameters: {'n_estimators': 133, 'max_depth': 9, 'min_samples_split': 7}. Best is trial 53 with value: 0.8520066665501187.
[I 2026-04-14 14:23:57,841] Trial 82 finished with value: 0.8515238661328766 and parameters: {'n_estimators': 121, 'max_depth': 9, 'min_samples_split': 6}. Best is trial 53 with value: 0.8520066665501187.
[I 2026-04-14 14:24:00,389] Trial 83 finished with value: 0.85031701077487 and parameters: {'n_estimators': 113, 'max_depth': 8, 'min_samples_split': 6}. Best is trial 53 with value: 0.8520066665501187.
[I 2026-04-14 14:24:03,247] Trial 84 finished with value: 0.8493514099403857 and parameters: {'n_estimators': 122, 'max_depth': 10, 'min_samples_split': 6}. Best is trial 53 with value: 0.8520066665501187.
[I 2026-04-14 14:24:06,037] Trial 85 finished with value: 0.848867735412551 and parameters: {'n_estimators': 140, 'max_depth': 7, 'min_samples_split': 7}. Best is trial 53 with value: 0.8520066665501187.
[I 2026-04-14 14:24:08,837] Trial 86 finished with value: 0.8479030086886592 and parameters: {'n_estimators': 105, 'max_depth': 11, 'min_samples_split': 8}. Best is trial 53 with value: 0.8520066665501187.
[I 2026-04-14 14:24:11,079] Trial 87 finished with value: 0.8401747055704154 and parameters: {'n_estimators': 119, 'max_depth': 6, 'min_samples_split': 6}. Best is trial 53 with value: 0.8520066665501187.
[I 2026-04-14 14:24:13,947] Trial 88 finished with value: 0.8524900497077559 and parameters: {'n_estimators': 124, 'max_depth': 9, 'min_samples_split': 5}. Best is trial 88 with value: 0.8524900497077559.
[I 2026-04-14 14:24:18,147] Trial 89 finished with value: 0.7394996008228294 and parameters: {'n_estimators': 112, 'max_depth': 25, 'min_samples_split': 4}. Best is trial 88 with value: 0.8524900497077559.
[I 2026-04-14 14:24:20,347] Trial 90 finished with value: 0.8466955705902578 and parameters: {'n_estimators': 82, 'max_depth': 11, 'min_samples_split': 5}. Best is trial 88 with value: 0.8524900497077559.
[I 2026-04-14 14:24:23,184] Trial 91 finished with value: 0.8522485038140359 and parameters: {'n_estimators': 126, 'max_depth': 9, 'min_samples_split': 5}. Best is trial 88 with value: 0.8524900497077559.
[I 2026-04-14 14:24:25,952] Trial 92 finished with value: 0.85031701077487 and parameters: {'n_estimators': 126, 'max_depth': 8, 'min_samples_split': 5}. Best is trial 88 with value: 0.8524900497077559.
[I 2026-04-14 14:24:28,674] Trial 93 finished with value: 0.8517657033967938 and parameters: {'n_estimators': 118, 'max_depth': 9, 'min_samples_split': 5}. Best is trial 88 with value: 0.8524900497077559.
[I 2026-04-14 14:24:31,645] Trial 94 finished with value: 0.8503173021450674 and parameters: {'n_estimators': 120, 'max_depth': 10, 'min_samples_split': 4}. Best is trial 88 with value: 0.8524900497077559.

,number,value,datetime_start,datetime_complete,duration,params_max_depth,params_min_samples_split,params_n_estimators,state
88,88,0.852490,2026-04-14 14:24:11.079564,2026-04-14 14:24:13.947634,0 days 00:00:02.868070,9,5,124,COMPLETE
91,91,0.852249,2026-04-14 14:24:20.348595,2026-04-14 14:24:23.184013,0 days 00:00:02.835418,9,5,126,COMPLETE
96,96,0.852008,2026-04-14 14:24:34.171165,2026-04-14 14:24:36.727563,0 days 00:00:02.556398,9,5,103,COMPLETE
53,53,0.852007,2026-04-14 14:22:34.775041,2026-04-14 14:22:37.142433,0 days 00:00:02.367392,9,6,122,COMPLETE
93,93,0.851766,2026-04-14 14:24:25.953199,2026-04-14 14:24:28.674108,0 days 00:00:02.720909,9,5,118,COMPLETE

In [ ]:
# Train using optimal parameters
model = RandomForestClassifier(
    class_weight='balanced',
    n_estimators=top_5_df.head(1)['params_n_estimators'].item(),
    max_depth=top_5_df.head(1)['params_max_depth'].item(),
    min_samples_split=top_5_df.head(1)['params_min_samples_split'].item(),
    random_state=random_state
)
model.fit(X_train_scaled, y_train)

RandomForestClassifier(class_weight='balanced', max_depth=9,
                       min_samples_split=5, n_estimators=124, random_state=42)

In [ ]:
y_pred = model.predict(X_test_scaled)

In [ ]:
print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.98      0.93      0.96     10355
           1       0.55      0.85      0.67      1035

    accuracy                           0.92     11390
   macro avg       0.77      0.89      0.81     11390
weighted avg       0.94      0.92      0.93     11390

### RF With unscaled Data and recall as param tuning metric

In [ ]:
def objective(trial):
    n_estimators = trial.suggest_int("n_estimators", 10, 200)
    max_depth = trial.suggest_int("max_depth", 2, 32, log=True)
    min_samples_split = trial.suggest_int("min_samples_split", 2, 10)
    
    model = RandomForestClassifier(
        class_weight='balanced',
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        random_state=random_state
    )
    
    scores = cross_val_score(
        model, 
        X=X_train, 
        y=y_train, 
        cv=cv,
        scoring='recall',
        n_jobs=-1,
    )
    recall = scores.mean()
    
    return recall


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

top_5_unscaled_df = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_unscaled_df)

[I 2026-04-14 14:51:01,029] A new study created in memory with name: no-name-81346362-09b7-423e-a1de-c904b184b1e7
[I 2026-04-14 14:51:01,605] Trial 0 finished with value: 0.8162730255298568 and parameters: {'n_estimators': 75, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 0 with value: 0.8162730255298568.
[I 2026-04-14 14:51:02,244] Trial 1 finished with value: 0.8042033064690012 and parameters: {'n_estimators': 61, 'max_depth': 3, 'min_samples_split': 9}. Best is trial 0 with value: 0.8162730255298568.
[I 2026-04-14 14:51:04,307] Trial 2 finished with value: 0.8232766909669411 and parameters: {'n_estimators': 71, 'max_depth': 17, 'min_samples_split': 10}. Best is trial 2 with value: 0.8232766909669411.
[I 2026-04-14 14:51:05,011] Trial 3 finished with value: 0.8046861068862432 and parameters: {'n_estimators': 49, 'max_depth': 5, 'min_samples_split': 5}. Best is trial 2 with value: 0.8232766909669411.
[I 2026-04-14 14:51:05,320] Trial 4 finished with value: 0.8399360733786704 and parameters: {'n_estimators': 14, 'max_depth': 2, 'min_samples_split': 7}. Best is trial 4 with value: 0.8399360733786704.
[I 2026-04-14 14:51:06,147] Trial 5 finished with value: 0.809514985169257 and parameters: {'n_estimators': 75, 'max_depth': 4, 'min_samples_split': 4}. Best is trial 4 with value: 0.8399360733786704.
[I 2026-04-14 14:51:06,724] Trial 6 finished with value: 0.8169973718408187 and parameters: {'n_estimators': 70, 'max_depth': 2, 'min_samples_split': 10}. Best is trial 4 with value: 0.8399360733786704.
[I 2026-04-14 14:51:07,239] Trial 7 finished with value: 0.8085493843347727 and parameters: {'n_estimators': 59, 'max_depth': 2, 'min_samples_split': 9}. Best is trial 4 with value: 0.8399360733786704.
[I 2026-04-14 14:51:08,004] Trial 8 finished with value: 0.8355864990705291 and parameters: {'n_estimators': 44, 'max_depth': 7, 'min_samples_split': 2}. Best is trial 4 with value: 0.8399360733786704.
[I 2026-04-14 14:51:08,785] Trial 9 finished with value: 0.816277396082819 and parameters: {'n_estimators': 22, 'max_depth': 17, 'min_samples_split': 7}. Best is trial 4 with value: 0.8399360733786704.
[I 2026-04-14 14:51:11,434] Trial 10 finished with value: 0.8512823202391566 and parameters: {'n_estimators': 157, 'max_depth': 9, 'min_samples_split': 7}. Best is trial 10 with value: 0.8512823202391566.
[I 2026-04-14 14:51:14,570] Trial 11 finished with value: 0.8481433891015892 and parameters: {'n_estimators': 176, 'max_depth': 10, 'min_samples_split': 7}. Best is trial 10 with value: 0.8512823202391566.
[I 2026-04-14 14:51:18,043] Trial 12 finished with value: 0.8459706415389009 and parameters: {'n_estimators': 176, 'max_depth': 11, 'min_samples_split': 7}. Best is trial 10 with value: 0.8512823202391566.
[I 2026-04-14 14:51:20,793] Trial 13 finished with value: 0.850799811192112 and parameters: {'n_estimators': 167, 'max_depth': 9, 'min_samples_split': 8}. Best is trial 10 with value: 0.8512823202391566.
[I 2026-04-14 14:51:24,885] Trial 14 finished with value: 0.7882697272192212 and parameters: {'n_estimators': 138, 'max_depth': 23, 'min_samples_split': 8}. Best is trial 10 with value: 0.8512823202391566.
[I 2026-04-14 14:51:27,039] Trial 15 finished with value: 0.8505585566685896 and parameters: {'n_estimators': 139, 'max_depth': 8, 'min_samples_split': 4}. Best is trial 10 with value: 0.8512823202391566.
[I 2026-04-14 14:51:30,360] Trial 16 finished with value: 0.8326929016392487 and parameters: {'n_estimators': 144, 'max_depth': 14, 'min_samples_split': 8}. Best is trial 10 with value: 0.8512823202391566.
[I 2026-04-14 14:51:32,461] Trial 17 finished with value: 0.837519157590485 and parameters: {'n_estimators': 198, 'max_depth': 5, 'min_samples_split': 5}. Best is trial 10 with value: 0.8512823202391566.
[I 2026-04-14 14:51:35,859] Trial 18 finished with value: 0.7592973316317313 and parameters: {'n_estimators': 109, 'max_depth': 28, 'min_samples_split': 8}. Best is trial 10 with value: 0.8512823202391566.
[I 2026-04-14 14:51:37,892] Trial 19 finished with value: 0.8479024259482644 and parameters: {'n_estimators': 108, 'max_depth': 10, 'min_samples_split': 6}. Best is trial 10 with value: 0.8512823202391566.
[I 2026-04-14 14:51:39,905] Trial 20 finished with value: 0.8442801116530596 and parameters: {'n_estimators': 162, 'max_depth': 6, 'min_samples_split': 9}. Best is trial 10 with value: 0.8512823202391566.
[I 2026-04-14 14:51:41,999] Trial 21 finished with value: 0.8486261895188314 and parameters: {'n_estimators': 135, 'max_depth': 8, 'min_samples_split': 3}. Best is trial 10 with value: 0.8512823202391566.
[I 2026-04-14 14:51:44,372] Trial 22 finished with value: 0.8508001025623095 and parameters: {'n_estimators': 158, 'max_depth': 8, 'min_samples_split': 4}. Best is trial 10 with value: 0.8512823202391566.
[I 2026-04-14 14:51:47,562] Trial 23 finished with value: 0.8423503668350787 and parameters: {'n_estimators': 156, 'max_depth': 12, 'min_samples_split': 5}. Best is trial 10 with value: 0.8512823202391566.
[I 2026-04-14 14:51:49,367] Trial 24 finished with value: 0.8329309510905987 and parameters: {'n_estimators': 199, 'max_depth': 4, 'min_samples_split': 3}. Best is trial 10 with value: 0.8512823202391566.
[I 2026-04-14 14:51:51,362] Trial 25 finished with value: 0.8493511185701881 and parameters: {'n_estimators': 124, 'max_depth': 8, 'min_samples_split': 6}. Best is trial 10 with value: 0.8512823202391566.
[I 2026-04-14 14:51:55,323] Trial 26 finished with value: 0.8297966818761908 and parameters: {'n_estimators': 173, 'max_depth': 14, 'min_samples_split': 4}. Best is trial 10 with value: 0.8512823202391566.
[I 2026-04-14 14:51:58,100] Trial 27 finished with value: 0.7602652634277955 and parameters: {'n_estimators': 92, 'max_depth': 21, 'min_samples_split': 2}. Best is trial 10 with value: 0.8512823202391566.
[I 2026-04-14 14:52:00,132] Trial 28 finished with value: 0.8445222402871744 and parameters: {'n_estimators': 163, 'max_depth': 6, 'min_samples_split': 8}. Best is trial 10 with value: 0.8512823202391566.
[I 2026-04-14 14:52:01,552] Trial 29 finished with value: 0.8090321847520148 and parameters: {'n_estimators': 185, 'max_depth': 3, 'min_samples_split': 6}. Best is trial 10 with value: 0.8512823202391566.
[I 2026-04-14 14:52:03,643] Trial 30 finished with value: 0.8512823202391567 and parameters: {'n_estimators': 120, 'max_depth': 9, 'min_samples_split': 5}. Best is trial 30 with value: 0.8512823202391567.
[I 2026-04-14 14:52:05,796] Trial 31 finished with value: 0.8515235747626789 and parameters: {'n_estimators': 122, 'max_depth': 9, 'min_samples_split': 5}. Best is trial 31 with value: 0.8515235747626789.
[I 2026-04-14 14:52:08,352] Trial 32 finished with value: 0.843075587256633 and parameters: {'n_estimators': 120, 'max_depth': 12, 'min_samples_split': 5}. Best is trial 31 with value: 0.8515235747626789.
[I 2026-04-14 14:52:10,227] Trial 33 finished with value: 0.8421079468307664 and parameters: {'n_estimators': 149, 'max_depth': 6, 'min_samples_split': 3}. Best is trial 31 with value: 0.8515235747626789.
[I 2026-04-14 14:52:12,682] Trial 34 finished with value: 0.8179661777474753 and parameters: {'n_estimators': 90, 'max_depth': 16, 'min_samples_split': 4}. Best is trial 31 with value: 0.8515235747626789.
[I 2026-04-14 14:52:14,456] Trial 35 finished with value: 0.8491092813062708 and parameters: {'n_estimators': 125, 'max_depth': 7, 'min_samples_split': 5}. Best is trial 31 with value: 0.8515235747626789.
[I 2026-04-14 14:52:15,613] Trial 36 finished with value: 0.8276186896499478 and parameters: {'n_estimators': 98, 'max_depth': 5, 'min_samples_split': 5}. Best is trial 31 with value: 0.8515235747626789.
[I 2026-04-14 14:52:18,140] Trial 37 finished with value: 0.8510410657156344 and parameters: {'n_estimators': 151, 'max_depth': 9, 'min_samples_split': 6}. Best is trial 31 with value: 0.8515235747626789.
[I 2026-04-14 14:52:19,267] Trial 38 finished with value: 0.8121693676683975 and parameters: {'n_estimators': 117, 'max_depth': 4, 'min_samples_split': 6}. Best is trial 31 with value: 0.8515235747626789.
[I 2026-04-14 14:52:22,512] Trial 39 finished with value: 0.8375226540328548 and parameters: {'n_estimators': 149, 'max_depth': 13, 'min_samples_split': 6}. Best is trial 31 with value: 0.8515235747626789.
[I 2026-04-14 14:52:24,972] Trial 40 finished with value: 0.8479027173184617 and parameters: {'n_estimators': 129, 'max_depth': 10, 'min_samples_split': 7}. Best is trial 31 with value: 0.8515235747626789.
[I 2026-04-14 14:52:27,560] Trial 41 finished with value: 0.8498330448768379 and parameters: {'n_estimators': 155, 'max_depth': 9, 'min_samples_split': 4}. Best is trial 31 with value: 0.8515235747626789.
[I 2026-04-14 14:52:30,273] Trial 42 finished with value: 0.8495920817235131 and parameters: {'n_estimators': 189, 'max_depth': 7, 'min_samples_split': 6}. Best is trial 31 with value: 0.8515235747626789.
[I 2026-04-14 14:52:32,646] Trial 43 finished with value: 0.8488686095231437 and parameters: {'n_estimators': 152, 'max_depth': 8, 'min_samples_split': 5}. Best is trial 31 with value: 0.8515235747626789.
[I 2026-04-14 14:52:35,820] Trial 44 finished with value: 0.8452474607087289 and parameters: {'n_estimators': 134, 'max_depth': 11, 'min_samples_split': 7}. Best is trial 31 with value: 0.8515235747626789.
[I 2026-04-14 14:52:38,185] Trial 45 finished with value: 0.8512823202391567 and parameters: {'n_estimators': 115, 'max_depth': 9, 'min_samples_split': 5}. Best is trial 31 with value: 0.8515235747626789.
[I 2026-04-14 14:52:40,384] Trial 46 finished with value: 0.8232775650775336 and parameters: {'n_estimators': 82, 'max_depth': 16, 'min_samples_split': 6}. Best is trial 31 with value: 0.8515235747626789.
[I 2026-04-14 14:52:42,362] Trial 47 finished with value: 0.8505576825579974 and parameters: {'n_estimators': 112, 'max_depth': 9, 'min_samples_split': 5}. Best is trial 31 with value: 0.8515235747626789.
[I 2026-04-14 14:52:43,767] Trial 48 finished with value: 0.8411414718856897 and parameters: {'n_estimators': 102, 'max_depth': 6, 'min_samples_split': 7}. Best is trial 31 with value: 0.8515235747626789.
[I 2026-04-14 14:52:46,451] Trial 49 finished with value: 0.8493514099403857 and parameters: {'n_estimators': 141, 'max_depth': 10, 'min_samples_split': 6}. Best is trial 31 with value: 0.8515235747626789.
[I 2026-04-14 14:52:47,965] Trial 50 finished with value: 0.8440406053507223 and parameters: {'n_estimators': 64, 'max_depth': 12, 'min_samples_split': 10}. Best is trial 31 with value: 0.8515235747626789.
[I 2026-04-14 14:52:50,294] Trial 51 finished with value: 0.8495917903533154 and parameters: {'n_estimators': 169, 'max_depth': 7, 'min_samples_split': 4}. Best is trial 31 with value: 0.8515235747626789.
[I 2026-04-14 14:52:52,514] Trial 52 finished with value: 0.8498330448768379 and parameters: {'n_estimators': 130, 'max_depth': 9, 'min_samples_split': 5}. Best is trial 31 with value: 0.8515235747626789.
[I 2026-04-14 14:52:54,384] Trial 53 finished with value: 0.8495923730937104 and parameters: {'n_estimators': 117, 'max_depth': 8, 'min_samples_split': 4}. Best is trial 31 with value: 0.8515235747626789.
[I 2026-04-14 14:52:57,868] Trial 54 finished with value: 0.8454878411216586 and parameters: {'n_estimators': 182, 'max_depth': 11, 'min_samples_split': 3}. Best is trial 31 with value: 0.8515235747626789.
[I 2026-04-14 14:52:59,739] Trial 55 finished with value: 0.841866109566849 and parameters: {'n_estimators': 145, 'max_depth': 6, 'min_samples_split': 7}. Best is trial 31 with value: 0.8515235747626789.
[I 2026-04-14 14:53:02,436] Trial 56 finished with value: 0.8498333362470353 and parameters: {'n_estimators': 161, 'max_depth': 9, 'min_samples_split': 5}. Best is trial 31 with value: 0.8515235747626789.
[I 2026-04-14 14:53:05,355] Trial 57 finished with value: 0.8022721048000327 and parameters: {'n_estimators': 103, 'max_depth': 18, 'min_samples_split': 4}. Best is trial 31 with value: 0.8515235747626789.
[I 2026-04-14 14:53:08,065] Trial 58 finished with value: 0.8322106839624016 and parameters: {'n_estimators': 113, 'max_depth': 14, 'min_samples_split': 6}. Best is trial 31 with value: 0.8515235747626789.
[I 2026-04-14 14:53:10,017] Trial 59 finished with value: 0.848867735412551 and parameters: {'n_estimators': 138, 'max_depth': 7, 'min_samples_split': 5}. Best is trial 31 with value: 0.8515235747626789.
[I 2026-04-14 14:53:10,501] Trial 60 finished with value: 0.8027551965874723 and parameters: {'n_estimators': 26, 'max_depth': 5, 'min_samples_split': 4}. Best is trial 31 with value: 0.8515235747626789.
[I 2026-04-14 14:53:13,558] Trial 61 finished with value: 0.8491092813062708 and parameters: {'n_estimators': 167, 'max_depth': 10, 'min_samples_split': 8}. Best is trial 31 with value: 0.8515235747626789.
[I 2026-04-14 14:53:16,309] Trial 62 finished with value: 0.8505579739281947 and parameters: {'n_estimators': 178, 'max_depth': 8, 'min_samples_split': 9}. Best is trial 31 with value: 0.8515235747626789.
[I 2026-04-14 14:53:19,486] Trial 63 finished with value: 0.8464537333263404 and parameters: {'n_estimators': 159, 'max_depth': 11, 'min_samples_split': 7}. Best is trial 31 with value: 0.8515235747626789.
[I 2026-04-14 14:53:22,685] Trial 64 finished with value: 0.8517657033967938 and parameters: {'n_estimators': 193, 'max_depth': 9, 'min_samples_split': 8}. Best is trial 64 with value: 0.8517657033967938.
[I 2026-04-14 14:53:25,517] Trial 65 finished with value: 0.8503161366642775 and parameters: {'n_estimators': 189, 'max_depth': 8, 'min_samples_split': 7}. Best is trial 64 with value: 0.8517657033967938.
[I 2026-04-14 14:53:27,774] Trial 66 finished with value: 0.850799811192112 and parameters: {'n_estimators': 124, 'max_depth': 9, 'min_samples_split': 9}. Best is trial 64 with value: 0.8517657033967938.
[I 2026-04-14 14:53:30,450] Trial 67 finished with value: 0.8495917903533154 and parameters: {'n_estimators': 194, 'max_depth': 7, 'min_samples_split': 8}. Best is trial 64 with value: 0.8517657033967938.
[I 2026-04-14 14:53:33,567] Trial 68 finished with value: 0.8416277687453017 and parameters: {'n_estimators': 146, 'max_depth': 12, 'min_samples_split': 6}. Best is trial 64 with value: 0.8517657033967938.
[I 2026-04-14 14:53:34,863] Trial 69 finished with value: 0.8387263043186891 and parameters: {'n_estimators': 95, 'max_depth': 6, 'min_samples_split': 5}. Best is trial 64 with value: 0.8517657033967938.
[I 2026-04-14 14:53:38,012] Trial 70 finished with value: 0.8322109753325991 and parameters: {'n_estimators': 132, 'max_depth': 14, 'min_samples_split': 3}. Best is trial 64 with value: 0.8517657033967938.
[I 2026-04-14 14:53:40,987] Trial 71 finished with value: 0.8517657033967938 and parameters: {'n_estimators': 175, 'max_depth': 9, 'min_samples_split': 8}. Best is trial 64 with value: 0.8517657033967938.
[I 2026-04-14 14:53:44,107] Trial 72 finished with value: 0.849350535829793 and parameters: {'n_estimators': 173, 'max_depth': 10, 'min_samples_split': 8}. Best is trial 64 with value: 0.8517657033967938.
[I 2026-04-14 14:53:47,049] Trial 73 finished with value: 0.8508001025623095 and parameters: {'n_estimators': 178, 'max_depth': 9, 'min_samples_split': 9}. Best is trial 64 with value: 0.8517657033967938.
[I 2026-04-14 14:53:50,539] Trial 74 finished with value: 0.8447643689212893 and parameters: {'n_estimators': 184, 'max_depth': 11, 'min_samples_split': 7}. Best is trial 64 with value: 0.8517657033967938.
[I 2026-04-14 14:53:52,803] Trial 75 finished with value: 0.8493505358297933 and parameters: {'n_estimators': 166, 'max_depth': 7, 'min_samples_split': 8}. Best is trial 64 with value: 0.8517657033967938.
[I 2026-04-14 14:53:56,898] Trial 76 finished with value: 0.8370395622454152 and parameters: {'n_estimators': 193, 'max_depth': 13, 'min_samples_split': 5}. Best is trial 64 with value: 0.8517657033967938.
[I 2026-04-14 14:53:58,319] Trial 77 finished with value: 0.8483852263655065 and parameters: {'n_estimators': 84, 'max_depth': 8, 'min_samples_split': 8}. Best is trial 64 with value: 0.8517657033967938.
[I 2026-04-14 14:54:01,172] Trial 78 finished with value: 0.8479024259482643 and parameters: {'n_estimators': 157, 'max_depth': 10, 'min_samples_split': 7}. Best is trial 64 with value: 0.8517657033967938.
[I 2026-04-14 14:54:02,130] Trial 79 finished with value: 0.809514985169257 and parameters: {'n_estimators': 152, 'max_depth': 2, 'min_samples_split': 5}. Best is trial 64 with value: 0.8517657033967938.
[I 2026-04-14 14:54:07,400] Trial 80 finished with value: 0.7139062254156396 and parameters: {'n_estimators': 172, 'max_depth': 32, 'min_samples_split': 6}. Best is trial 64 with value: 0.8517657033967938.
[I 2026-04-14 14:54:10,361] Trial 81 finished with value: 0.8508001025623095 and parameters: {'n_estimators': 178, 'max_depth': 9, 'min_samples_split': 9}. Best is trial 64 with value: 0.8517657033967938.
[I 2026-04-14 14:54:13,319] Trial 82 finished with value: 0.852006957920316 and parameters: {'n_estimators': 181, 'max_depth': 9, 'min_samples_split': 10}. Best is trial 82 with value: 0.852006957920316.
[I 2026-04-14 14:54:15,026] Trial 83 finished with value: 0.8493514099403857 and parameters: {'n_estimators': 108, 'max_depth': 8, 'min_samples_split': 10}. Best is trial 82 with value: 0.852006957920316.
[I 2026-04-14 14:54:17,680] Trial 84 finished with value: 0.8495914989831179 and parameters: {'n_estimators': 196, 'max_depth': 7, 'min_samples_split': 10}. Best is trial 82 with value: 0.852006957920316.
[I 2026-04-14 14:54:20,992] Trial 85 finished with value: 0.8491092813062708 and parameters: {'n_estimators': 188, 'max_depth': 10, 'min_samples_split': 6}. Best is trial 82 with value: 0.852006957920316.
[I 2026-04-14 14:54:23,391] Trial 86 finished with value: 0.8476605886843471 and parameters: {'n_estimators': 122, 'max_depth': 11, 'min_samples_split': 9}. Best is trial 82 with value: 0.852006957920316.
[I 2026-04-14 14:54:26,949] Trial 87 finished with value: 0.8370398536156127 and parameters: {'n_estimators': 165, 'max_depth': 13, 'min_samples_split': 5}. Best is trial 82 with value: 0.852006957920316.
[I 2026-04-14 14:54:30,241] Trial 88 finished with value: 0.8493505358297933 and parameters: {'n_estimators': 200, 'max_depth': 9, 'min_samples_split': 4}. Best is trial 82 with value: 0.852006957920316.
[I 2026-04-14 14:54:32,454] Trial 89 finished with value: 0.8498339189874302 and parameters: {'n_estimators': 141, 'max_depth': 8, 'min_samples_split': 10}. Best is trial 82 with value: 0.852006957920316.
[I 2026-04-14 14:54:33,887] Trial 90 finished with value: 0.828585455965222 and parameters: {'n_estimators': 128, 'max_depth': 5, 'min_samples_split': 6}. Best is trial 82 with value: 0.852006957920316.
[I 2026-04-14 14:54:37,050] Trial 91 finished with value: 0.8507995198219145 and parameters: {'n_estimators': 180, 'max_depth': 10, 'min_samples_split': 9}. Best is trial 82 with value: 0.852006957920316.
[I 2026-04-14 14:54:39,923] Trial 92 finished with value: 0.8498339189874302 and parameters: {'n_estimators': 171, 'max_depth': 9, 'min_samples_split': 9}. Best is trial 82 with value: 0.852006957920316.
[I 2026-04-14 14:54:42,850] Trial 93 finished with value: 0.8517657033967938 and parameters: {'n_estimators': 175, 'max_depth': 9, 'min_samples_split': 8}. Best is trial 82 with value: 0.852006957920316.
[I 2026-04-14 14:54:45,375] Trial 94 finished with value: 0.8498330448768379 and parameters: {'n_estimators': 185, 'max_depth': 7, 'min_samples_split': 8}. Best is trial 82 with value: 0.852006957920316.
[I 2026-04-14 14:54:48,481] Trial 95 finished with value: 0.8452465865981365 and parameters: {'n_estimators': 162, 'max_depth': 11, 'min_samples_split': 8}. Best is trial 82 with value: 0.852006957920316.
[I 2026-04-14 14:54:50,808] Trial 96 finished with value: 0.849592081723513 and parameters: {'n_estimators': 153, 'max_depth': 8, 'min_samples_split': 7}. Best is trial 82 with value: 0.852006957920316.

,number,value,datetime_start,datetime_complete,duration,params_max_depth,params_min_samples_split,params_n_estimators,state
82,82,0.852007,2026-04-14 14:54:10.362024,2026-04-14 14:54:13.319674,0 days 00:00:02.957650,9,10,181,COMPLETE
93,93,0.851766,2026-04-14 14:54:39.923495,2026-04-14 14:54:42.850984,0 days 00:00:02.927489,9,8,175,COMPLETE
64,64,0.851766,2026-04-14 14:53:19.486939,2026-04-14 14:53:22.685829,0 days 00:00:03.198890,9,8,193,COMPLETE
71,71,0.851766,2026-04-14 14:53:38.013142,2026-04-14 14:53:40.987306,0 days 00:00:02.974164,9,8,175,COMPLETE
97,97,0.851766,2026-04-14 14:54:50.809066,2026-04-14 14:54:53.633662,0 days 00:00:02.824596,9,8,175,COMPLETE

In [ ]:
# Train using optimal parameters
model = RandomForestClassifier(
    class_weight='balanced',
    n_estimators=top_5_unscaled_df.head(1)['params_n_estimators'].item(),
    max_depth=top_5_unscaled_df.head(1)['params_max_depth'].item(),
    min_samples_split=top_5_unscaled_df.head(1)['params_min_samples_split'].item(),
    random_state=random_state
)
model.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', max_depth=9,
                       min_samples_split=10, n_estimators=181, random_state=42)

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.98      0.93      0.96     10355
           1       0.55      0.84      0.67      1035

    accuracy                           0.92     11390
   macro avg       0.77      0.89      0.81     11390
weighted avg       0.94      0.92      0.93     11390

In [ ]:
recall_model_report_df = classification_report(y_test, y_pred, output_dict=True)

### No scaling, f1 as eval metric

In [ ]:
# Parameter tuning
import optuna
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score


def objective(trial):
    n_estimators = trial.suggest_int("n_estimators", 10, 200)
    max_depth = trial.suggest_int("max_depth", 2, 32, log=True)
    min_samples_split = trial.suggest_int("min_samples_split", 2, 10)
    
    model = RandomForestClassifier(
        class_weight='balanced',
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        random_state=random_state
    )
    
    scores = cross_val_score(
        model, 
        X=X_train, 
        y=y_train, 
        cv=cv,
        scoring="f1",
        n_jobs=-1,
    )
    f1 = scores.mean()
    return f1


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

top_5_f1_df = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_f1_df)

[I 2026-04-14 14:44:46,858] A new study created in memory with name: no-name-bd465fdb-5a7e-40a5-8419-cd9e25ede6c2
[I 2026-04-14 14:44:48,804] Trial 0 finished with value: 0.6689164323718346 and parameters: {'n_estimators': 35, 'max_depth': 5, 'min_samples_split': 10}. Best is trial 0 with value: 0.6689164323718346.
[I 2026-04-14 14:44:50,992] Trial 1 finished with value: 0.667854481318131 and parameters: {'n_estimators': 115, 'max_depth': 4, 'min_samples_split': 4}. Best is trial 0 with value: 0.6689164323718346.
[I 2026-04-14 14:44:54,599] Trial 2 finished with value: 0.6905742563524027 and parameters: {'n_estimators': 92, 'max_depth': 18, 'min_samples_split': 3}. Best is trial 2 with value: 0.6905742563524027.
[I 2026-04-14 14:44:56,789] Trial 3 finished with value: 0.6655179729953378 and parameters: {'n_estimators': 95, 'max_depth': 5, 'min_samples_split': 5}. Best is trial 2 with value: 0.6905742563524027.
[I 2026-04-14 14:44:59,206] Trial 4 finished with value: 0.6888239707782965 and parameters: {'n_estimators': 81, 'max_depth': 20, 'min_samples_split': 6}. Best is trial 2 with value: 0.6905742563524027.
[I 2026-04-14 14:45:00,215] Trial 5 finished with value: 0.6689580888698118 and parameters: {'n_estimators': 81, 'max_depth': 5, 'min_samples_split': 10}. Best is trial 2 with value: 0.6905742563524027.
[I 2026-04-14 14:45:01,429] Trial 6 finished with value: 0.6789451792610242 and parameters: {'n_estimators': 43, 'max_depth': 12, 'min_samples_split': 2}. Best is trial 2 with value: 0.6905742563524027.
[I 2026-04-14 14:45:02,135] Trial 7 finished with value: 0.6693311723779061 and parameters: {'n_estimators': 57, 'max_depth': 4, 'min_samples_split': 6}. Best is trial 2 with value: 0.6905742563524027.
[I 2026-04-14 14:45:03,600] Trial 8 finished with value: 0.6608671024790465 and parameters: {'n_estimators': 97, 'max_depth': 7, 'min_samples_split': 7}. Best is trial 2 with value: 0.6905742563524027.
[I 2026-04-14 14:45:08,973] Trial 9 finished with value: 0.6572923732539245 and parameters: {'n_estimators': 173, 'max_depth': 26, 'min_samples_split': 3}. Best is trial 2 with value: 0.6905742563524027.
[I 2026-04-14 14:45:09,952] Trial 10 finished with value: 0.6461335538407518 and parameters: {'n_estimators': 148, 'max_depth': 2, 'min_samples_split': 2}. Best is trial 2 with value: 0.6905742563524027.
[I 2026-04-14 14:45:10,513] Trial 11 finished with value: 0.6567132308015359 and parameters: {'n_estimators': 11, 'max_depth': 29, 'min_samples_split': 8}. Best is trial 2 with value: 0.6905742563524027.
[I 2026-04-14 14:45:13,953] Trial 12 finished with value: 0.6885603681939719 and parameters: {'n_estimators': 130, 'max_depth': 17, 'min_samples_split': 5}. Best is trial 2 with value: 0.6905742563524027.
[I 2026-04-14 14:45:15,758] Trial 13 finished with value: 0.6852506020231589 and parameters: {'n_estimators': 69, 'max_depth': 15, 'min_samples_split': 8}. Best is trial 2 with value: 0.6905742563524027.
[I 2026-04-14 14:45:19,006] Trial 14 finished with value: 0.6621313254261243 and parameters: {'n_estimators': 189, 'max_depth': 9, 'min_samples_split': 4}. Best is trial 2 with value: 0.6905742563524027.
[I 2026-04-14 14:45:23,012] Trial 15 finished with value: 0.6752365636419118 and parameters: {'n_estimators': 132, 'max_depth': 24, 'min_samples_split': 6}. Best is trial 2 with value: 0.6905742563524027.
[I 2026-04-14 14:45:25,058] Trial 16 finished with value: 0.6880822970387469 and parameters: {'n_estimators': 80, 'max_depth': 15, 'min_samples_split': 3}. Best is trial 2 with value: 0.6905742563524027.
[I 2026-04-14 14:45:28,475] Trial 17 finished with value: 0.6834984231746521 and parameters: {'n_estimators': 114, 'max_depth': 22, 'min_samples_split': 8}. Best is trial 2 with value: 0.6905742563524027.
[I 2026-04-14 14:45:31,222] Trial 18 finished with value: 0.6645270083973858 and parameters: {'n_estimators': 149, 'max_depth': 10, 'min_samples_split': 4}. Best is trial 2 with value: 0.6905742563524027.
[I 2026-04-14 14:45:32,623] Trial 19 finished with value: 0.6872214440061214 and parameters: {'n_estimators': 44, 'max_depth': 19, 'min_samples_split': 6}. Best is trial 2 with value: 0.6905742563524027.
[I 2026-04-14 14:45:32,917] Trial 20 finished with value: 0.2941464952633757 and parameters: {'n_estimators': 13, 'max_depth': 2, 'min_samples_split': 9}. Best is trial 2 with value: 0.6905742563524027.
[I 2026-04-14 14:45:37,225] Trial 21 finished with value: 0.6400396238878596 and parameters: {'n_estimators': 135, 'max_depth': 32, 'min_samples_split': 5}. Best is trial 2 with value: 0.6905742563524027.
[I 2026-04-14 14:45:40,001] Trial 22 finished with value: 0.6872571445129589 and parameters: {'n_estimators': 107, 'max_depth': 15, 'min_samples_split': 5}. Best is trial 2 with value: 0.6905742563524027.
[I 2026-04-14 14:45:43,654] Trial 23 finished with value: 0.6902943385180034 and parameters: {'n_estimators': 129, 'max_depth': 19, 'min_samples_split': 3}. Best is trial 2 with value: 0.6905742563524027.
[I 2026-04-14 14:45:45,312] Trial 24 finished with value: 0.6698949611828121 and parameters: {'n_estimators': 79, 'max_depth': 11, 'min_samples_split': 3}. Best is trial 2 with value: 0.6905742563524027.
[I 2026-04-14 14:45:49,990] Trial 25 finished with value: 0.6917356919827584 and parameters: {'n_estimators': 164, 'max_depth': 19, 'min_samples_split': 2}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:45:52,472] Trial 26 finished with value: 0.6628641349169481 and parameters: {'n_estimators': 161, 'max_depth': 8, 'min_samples_split': 2}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:45:56,680] Trial 27 finished with value: 0.6851917591544909 and parameters: {'n_estimators': 193, 'max_depth': 13, 'min_samples_split': 3}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:46:01,559] Trial 28 finished with value: 0.6886674748756307 and parameters: {'n_estimators': 174, 'max_depth': 20, 'min_samples_split': 2}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:46:05,328] Trial 29 finished with value: 0.6644261061467609 and parameters: {'n_estimators': 123, 'max_depth': 25, 'min_samples_split': 3}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:46:08,547] Trial 30 finished with value: 0.683209429764161 and parameters: {'n_estimators': 147, 'max_depth': 13, 'min_samples_split': 4}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:46:11,157] Trial 31 finished with value: 0.6887176386088202 and parameters: {'n_estimators': 94, 'max_depth': 18, 'min_samples_split': 2}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:46:13,107] Trial 32 finished with value: 0.6858277533356544 and parameters: {'n_estimators': 62, 'max_depth': 20, 'min_samples_split': 4}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:46:16,470] Trial 33 finished with value: 0.6385697171887286 and parameters: {'n_estimators': 105, 'max_depth': 28, 'min_samples_split': 3}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:46:18,808] Trial 34 finished with value: 0.6870314689702013 and parameters: {'n_estimators': 87, 'max_depth': 16, 'min_samples_split': 7}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:46:22,260] Trial 35 finished with value: 0.6799667639635387 and parameters: {'n_estimators': 119, 'max_depth': 22, 'min_samples_split': 4}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:46:23,649] Trial 36 finished with value: 0.6522543469275287 and parameters: {'n_estimators': 163, 'max_depth': 3, 'min_samples_split': 10}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:46:26,041] Trial 37 finished with value: 0.6072229499008124 and parameters: {'n_estimators': 70, 'max_depth': 32, 'min_samples_split': 2}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:46:27,271] Trial 38 finished with value: 0.6635248605629753 and parameters: {'n_estimators': 91, 'max_depth': 6, 'min_samples_split': 7}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:46:28,520] Trial 39 finished with value: 0.6840821772017329 and parameters: {'n_estimators': 48, 'max_depth': 12, 'min_samples_split': 3}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:46:29,238] Trial 40 finished with value: 0.6660061893181288 and parameters: {'n_estimators': 31, 'max_depth': 9, 'min_samples_split': 6}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:46:31,973] Trial 41 finished with value: 0.6892527599445065 and parameters: {'n_estimators': 100, 'max_depth': 18, 'min_samples_split': 2}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:46:35,206] Trial 42 finished with value: 0.6731284595250001 and parameters: {'n_estimators': 106, 'max_depth': 23, 'min_samples_split': 2}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:46:38,944] Trial 43 finished with value: 0.6886785790298859 and parameters: {'n_estimators': 141, 'max_depth': 17, 'min_samples_split': 2}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:46:41,258] Trial 44 finished with value: 0.6857609402342912 and parameters: {'n_estimators': 98, 'max_depth': 14, 'min_samples_split': 3}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:46:44,444] Trial 45 finished with value: 0.6882339250839001 and parameters: {'n_estimators': 113, 'max_depth': 20, 'min_samples_split': 2}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:46:46,822] Trial 46 finished with value: 0.6562899810953275 and parameters: {'n_estimators': 73, 'max_depth': 27, 'min_samples_split': 4}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:46:50,608] Trial 47 finished with value: 0.6700122335442368 and parameters: {'n_estimators': 200, 'max_depth': 11, 'min_samples_split': 5}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:46:54,098] Trial 48 finished with value: 0.6872501461315146 and parameters: {'n_estimators': 127, 'max_depth': 18, 'min_samples_split': 9}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:46:56,018] Trial 49 finished with value: 0.6783842139023621 and parameters: {'n_estimators': 58, 'max_depth': 22, 'min_samples_split': 3}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:46:57,780] Trial 50 finished with value: 0.6558331095138449 and parameters: {'n_estimators': 178, 'max_depth': 4, 'min_samples_split': 2}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:47:00,829] Trial 51 finished with value: 0.6890651892961971 and parameters: {'n_estimators': 97, 'max_depth': 17, 'min_samples_split': 2}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:47:03,875] Trial 52 finished with value: 0.6893075508598343 and parameters: {'n_estimators': 99, 'max_depth': 16, 'min_samples_split': 2}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:47:06,987] Trial 53 finished with value: 0.6894587045387677 and parameters: {'n_estimators': 101, 'max_depth': 16, 'min_samples_split': 2}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:47:09,578] Trial 54 finished with value: 0.6861158557078625 and parameters: {'n_estimators': 88, 'max_depth': 14, 'min_samples_split': 3}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:47:12,837] Trial 55 finished with value: 0.6888448107784508 and parameters: {'n_estimators': 103, 'max_depth': 15, 'min_samples_split': 2}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:47:15,967] Trial 56 finished with value: 0.6787850849198002 and parameters: {'n_estimators': 116, 'max_depth': 12, 'min_samples_split': 3}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:47:22,326] Trial 57 finished with value: 0.6553688614671558 and parameters: {'n_estimators': 158, 'max_depth': 25, 'min_samples_split': 2}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:47:24,373] Trial 58 finished with value: 0.6640824923468774 and parameters: {'n_estimators': 83, 'max_depth': 10, 'min_samples_split': 2}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:47:27,787] Trial 59 finished with value: 0.689439138320691 and parameters: {'n_estimators': 110, 'max_depth': 16, 'min_samples_split': 3}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:47:30,028] Trial 60 finished with value: 0.6650503304967457 and parameters: {'n_estimators': 127, 'max_depth': 6, 'min_samples_split': 4}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:47:33,475] Trial 61 finished with value: 0.6894295573652645 and parameters: {'n_estimators': 112, 'max_depth': 16, 'min_samples_split': 3}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:47:37,082] Trial 62 finished with value: 0.6894295573652645 and parameters: {'n_estimators': 112, 'max_depth': 16, 'min_samples_split': 3}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:47:41,046] Trial 63 finished with value: 0.6850408184087634 and parameters: {'n_estimators': 136, 'max_depth': 13, 'min_samples_split': 3}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:47:44,308] Trial 64 finished with value: 0.688638219661238 and parameters: {'n_estimators': 112, 'max_depth': 20, 'min_samples_split': 3}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:47:47,127] Trial 65 finished with value: 0.6892304362323524 and parameters: {'n_estimators': 109, 'max_depth': 16, 'min_samples_split': 3}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:47:50,557] Trial 66 finished with value: 0.6854265927736384 and parameters: {'n_estimators': 119, 'max_depth': 21, 'min_samples_split': 4}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:47:53,030] Trial 67 finished with value: 0.6702231623381121 and parameters: {'n_estimators': 121, 'max_depth': 11, 'min_samples_split': 3}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:47:57,618] Trial 68 finished with value: 0.6738781954901397 and parameters: {'n_estimators': 152, 'max_depth': 24, 'min_samples_split': 4}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:48:00,124] Trial 69 finished with value: 0.6268363592025077 and parameters: {'n_estimators': 75, 'max_depth': 30, 'min_samples_split': 3}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:48:03,411] Trial 70 finished with value: 0.685655655070338 and parameters: {'n_estimators': 139, 'max_depth': 14, 'min_samples_split': 4}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:48:05,985] Trial 71 finished with value: 0.6887234848044812 and parameters: {'n_estimators': 92, 'max_depth': 18, 'min_samples_split': 2}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:48:08,853] Trial 72 finished with value: 0.6892304362323524 and parameters: {'n_estimators': 109, 'max_depth': 16, 'min_samples_split': 3}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:48:09,781] Trial 73 finished with value: 0.6572426757917427 and parameters: {'n_estimators': 102, 'max_depth': 3, 'min_samples_split': 2}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:48:13,562] Trial 74 finished with value: 0.6905049918927524 and parameters: {'n_estimators': 128, 'max_depth': 19, 'min_samples_split': 3}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:48:17,783] Trial 75 finished with value: 0.6884762311840558 and parameters: {'n_estimators': 131, 'max_depth': 20, 'min_samples_split': 3}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:48:20,619] Trial 76 finished with value: 0.6827617744047016 and parameters: {'n_estimators': 125, 'max_depth': 13, 'min_samples_split': 5}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:48:25,325] Trial 77 finished with value: 0.6897126307520576 and parameters: {'n_estimators': 169, 'max_depth': 19, 'min_samples_split': 4}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:48:30,985] Trial 78 finished with value: 0.6615075915513654 and parameters: {'n_estimators': 185, 'max_depth': 26, 'min_samples_split': 4}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:48:35,379] Trial 79 finished with value: 0.6778244575824919 and parameters: {'n_estimators': 144, 'max_depth': 23, 'min_samples_split': 3}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:48:40,062] Trial 80 finished with value: 0.6895771430637095 and parameters: {'n_estimators': 166, 'max_depth': 19, 'min_samples_split': 4}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:48:44,658] Trial 81 finished with value: 0.6901753653309628 and parameters: {'n_estimators': 163, 'max_depth': 19, 'min_samples_split': 5}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:48:49,364] Trial 82 finished with value: 0.6902441190312657 and parameters: {'n_estimators': 170, 'max_depth': 19, 'min_samples_split': 5}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:48:54,161] Trial 83 finished with value: 0.6846136901204539 and parameters: {'n_estimators': 168, 'max_depth': 21, 'min_samples_split': 5}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:48:58,426] Trial 84 finished with value: 0.6900819075839867 and parameters: {'n_estimators': 155, 'max_depth': 19, 'min_samples_split': 5}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:49:02,729] Trial 85 finished with value: 0.6879494487366435 and parameters: {'n_estimators': 155, 'max_depth': 19, 'min_samples_split': 6}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:49:07,349] Trial 86 finished with value: 0.6901779565935231 and parameters: {'n_estimators': 165, 'max_depth': 19, 'min_samples_split': 5}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:49:12,652] Trial 87 finished with value: 0.6793534371083089 and parameters: {'n_estimators': 173, 'max_depth': 23, 'min_samples_split': 5}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:49:18,403] Trial 88 finished with value: 0.6441520885389173 and parameters: {'n_estimators': 182, 'max_depth': 30, 'min_samples_split': 5}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:49:22,766] Trial 89 finished with value: 0.6883574334284932 and parameters: {'n_estimators': 161, 'max_depth': 18, 'min_samples_split': 6}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:49:27,863] Trial 90 finished with value: 0.6530856500430858 and parameters: {'n_estimators': 167, 'max_depth': 28, 'min_samples_split': 5}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:49:32,281] Trial 91 finished with value: 0.6855118786899169 and parameters: {'n_estimators': 151, 'max_depth': 21, 'min_samples_split': 5}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:49:36,880] Trial 92 finished with value: 0.6887555030722945 and parameters: {'n_estimators': 169, 'max_depth': 18, 'min_samples_split': 4}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:49:42,633] Trial 93 finished with value: 0.6903906411006462 and parameters: {'n_estimators': 177, 'max_depth': 19, 'min_samples_split': 5}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:49:48,801] Trial 94 finished with value: 0.6753979937005778 and parameters: {'n_estimators': 177, 'max_depth': 24, 'min_samples_split': 6}. Best is trial 25 with value: 0.6917356919827584.
[I 2026-04-14 14:49:55,398] Trial 95 finished with value: 0.6822644839363629 and parameters: {'n_estimators': 194, 'max_depth': 22, 'min_samples_split': 5}. Best is trial 25 with value: 0.6917356919827584.

,number,value,datetime_start,datetime_complete,duration,params_max_depth,params_min_samples_split,params_n_estimators,state
25,25,0.691736,2026-04-14 14:45:45.313099,2026-04-14 14:45:49.990891,0 days 00:00:04.677792,19,2,164,COMPLETE
2,2,0.690574,2026-04-14 14:44:50.993420,2026-04-14 14:44:54.599128,0 days 00:00:03.605708,18,3,92,COMPLETE
74,74,0.690505,2026-04-14 14:48:09.782988,2026-04-14 14:48:13.562496,0 days 00:00:03.779508,19,3,128,COMPLETE
93,93,0.690391,2026-04-14 14:49:36.881259,2026-04-14 14:49:42.633462,0 days 00:00:05.752203,19,5,177,COMPLETE
23,23,0.690294,2026-04-14 14:45:40.002773,2026-04-14 14:45:43.654819,0 days 00:00:03.652046,19,3,129,COMPLETE

In [ ]:
# Train using optimal parameters
model = RandomForestClassifier(
    class_weight='balanced',
    n_estimators=top_5_f1_df.head(1)['params_n_estimators'].item(),
    max_depth=top_5_f1_df.head(1)['params_max_depth'].item(),
    min_samples_split=top_5_f1_df.head(1)['params_min_samples_split'].item(),
    random_state=random_state
)
model.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', max_depth=19, n_estimators=164,
                       random_state=42)

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.98      0.95      0.96     10355
           1       0.62      0.79      0.69      1035

    accuracy                           0.94     11390
   macro avg       0.80      0.87      0.83     11390
weighted avg       0.95      0.94      0.94     11390

In [ ]:
f1_model_report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)

### Compare Models

In [ ]:
# 2. Convert and transpose
recall_report_df = pd.DataFrame(recall_model_report_df).transpose()
f1_report_df = pd.DataFrame(f1_model_report).transpose()

# 3. Combine multiple reports (e.g., adding a 'Model' column for identification)
combined_df = pd.concat([recall_report_df, f1_report_df], keys=['RF optimized for Recall', 'RF optimized for F1'])

In [ ]:
combined_df

                                      precision    recall  f1-score  \
RF optimized for Recall 0              0.983590  0.931917  0.957056
                        1              0.553515  0.844444  0.668707
                        accuracy       0.923968  0.923968  0.923968
                        macro avg      0.768552  0.888181  0.812882
                        weighted avg   0.944509  0.923968  0.930854
RF optimized for F1     0              0.978542  0.951231  0.964693
                        1              0.618580  0.791304  0.694362
                        accuracy       0.936699  0.936699  0.936699
                        macro avg      0.798561  0.871268  0.829528
                        weighted avg   0.945832  0.936699  0.940128

                                           support
RF optimized for Recall 0             10355.000000
                        1              1035.000000
                        accuracy          0.923968
                        macro avg     11390.000000
                        weighted avg  11390.000000
RF optimized for F1     0             10355.000000
                        1              1035.000000
                        accuracy          0.936699
                        macro avg     11390.000000
                        weighted avg  11390.000000

In [ ]:
model.feature_importances_

array([6.62856785e-02, 6.05995047e-02, 9.03900169e-02, 1.01445840e-01,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       2.60059656e-04, 1.78374884e-03, 2.60533729e-04, 2.09601415e-04,
       1.49968033e-03, 2.93575262e-04, 4.40192161e-04, 3.55538205e-04,
       4.22583210e-03, 8.52128064e-04, 3.51972169e-04, 3.02110751e-04,
       9.16247728e-04, 3.06642333e-04, 3.21460516e-04, 1.69076506e-04,
       1.24906420e-03, 2.91538203e-04, 2.06885534e-04, 1.35531697e-03,
       2.81877643e-04, 3.16866904e-04, 3.73858263e-04, 4.76218125e-03,
       8.74444662e-04, 2.62872159e-04, 2.77801866e-04, 1.32006387e-03,
       2.70280515e-04, 5.92506764e-04, 3.84747851e-01, 1.02914776e-03,
       1.87227051e-02, 1.01112937e-01, 6.69776568e-02, 1.84186719e-02,
       9.61421113e-03, 3.74866401e-02, 1.81851808e-02])

In [ ]:
pd.set_option('display.max_rows', None)

In [ ]:
importances = model.feature_importances_
feature_names = df.drop(columns='Is Laundering').columns
feature_imp_df = pd.DataFrame({'Feature': feature_names, 'Gini Importance': importances}).sort_values(
    'Gini Importance', ascending=False)
feature_imp_df

                                      Feature  Gini Importance
94                         Payment Format_ACH         0.384748
3                             Amount_Paid_USD         0.101446
97                      Payment Format_Cheque         0.101113
2                         Amount_Received_USD         0.090390
98                 Payment Format_Credit Card         0.066978
0                             Amount Received         0.066286
1                                 Amount Paid         0.060600
101                              Account_Same         0.037487
96                        Payment Format_Cash         0.018723
99                Payment Format_Reinvestment         0.018419
102                                 Bank_Same         0.018185
100                       Payment Format_Wire         0.009614
87               Payment Currency_Saudi Riyal         0.004762
72             Receiving Currency_Saudi Riyal         0.004226
65                 Receiving Currency_Bitcoin         0.001784
68                    Receiving Currency_Euro         0.001500
83                      Payment Currency_Euro         0.001355
91                 Payment Currency_US Dollar         0.001320
80                   Payment Currency_Bitcoin         0.001249
95                     Payment Format_Bitcoin         0.001029
76               Receiving Currency_US Dollar         0.000916
88                    Payment Currency_Shekel         0.000874
73                  Receiving Currency_Shekel         0.000852
93                      Payment Currency_Yuan         0.000593
70                   Receiving Currency_Ruble         0.000440
86                     Payment Currency_Rupee         0.000374
71                   Receiving Currency_Rupee         0.000356
74             Receiving Currency_Swiss Franc         0.000352
78                    Receiving Currency_Yuan         0.000321
85                     Payment Currency_Ruble         0.000317
77                     Receiving Currency_Yen         0.000307
75                Receiving Currency_UK Pound         0.000302
69            Receiving Currency_Mexican Peso         0.000294
81               Payment Currency_Brazil Real         0.000292
84              Payment Currency_Mexican Peso         0.000282
90                  Payment Currency_UK Pound         0.000278
92                       Payment Currency_Yen         0.000270
89               Payment Currency_Swiss Franc         0.000263
66             Receiving Currency_Brazil Real         0.000261
64       Receiving Currency_Australian Dollar         0.000260
67         Receiving Currency_Canadian Dollar         0.000210
82           Payment Currency_Canadian Dollar         0.000207
79         Payment Currency_Australian Dollar         0.000169
38              UK Pound_Amount_Received_Mean         0.000000
37                UK Pound_Amount_Paid_Median         0.000000
36                  UK Pound_Amount_Paid_Mean         0.000000
31                 Yen_Amount_Received_Median         0.000000
30                   Yen_Amount_Received_Mean         0.000000
29                     Yen_Amount_Paid_Median         0.000000
28                       Yen_Amount_Paid_Mean         0.000000
27               Rupee_Amount_Received_Median         0.000000
26                 Rupee_Amount_Received_Mean         0.000000
25                   Rupee_Amount_Paid_Median         0.000000
24                     Rupee_Amount_Paid_Mean         0.000000
23                Yuan_Amount_Received_Median         0.000000
22                  Yuan_Amount_Received_Mean         0.000000
21                    Yuan_Amount_Paid_Median         0.000000
20                      Yuan_Amount_Paid_Mean         0.000000
19   Australian Dollar_Amount_Received_Median         0.000000
18     Australian Dollar_Amount_Received_Mean         0.000000
17       Australian Dollar_Amount_Paid_Median         0.000000
16         Australian Dollar_Amount_Paid_Mean         0.000000
15                Euro_Amount_Received_Median         0.000000
14                  Euro_Amount_Received_Mean         0.000000
13                    Euro_Amount_Paid_Median         0.000000
12                      Euro_Amount_Paid_Mean         0.000000
11             Bitcoin_Amount_Received_Median         0.000000
10               Bitcoin_Amount_Received_Mean         0.000000
9                  Bitcoin_Amount_Paid_Median         0.000000
8                    Bitcoin_Amount_Paid_Mean         0.000000
7            US Dollar_Amount_Received_Median         0.000000
6              US Dollar_Amount_Received_Mean         0.000000
5                US Dollar_Amount_Paid_Median         0.000000
4                  US Dollar_Amount_Paid_Mean         0.000000
35        Mexican Peso_Amount_Received_Median         0.000000
34          Mexican Peso_Amount_Received_Mean         0.000000
33            Mexican Peso_Amount_Paid_Median         0.000000
32              Mexican Peso_Amount_Paid_Mean         0.000000
63              Shekel_Amount_Received_Median         0.000000
55         Brazil Real_Amount_Received_Median         0.000000
56               Saudi Riyal_Amount_Paid_Mean         0.000000
57             Saudi Riyal_Amount_Paid_Median         0.000000
58           Saudi Riyal_Amount_Received_Mean         0.000000
59         Saudi Riyal_Amount_Received_Median         0.000000
60                    Shekel_Amount_Paid_Mean         0.000000
61                  Shekel_Amount_Paid_Median         0.000000
62                Shekel_Amount_Received_Mean         0.000000
46       Canadian Dollar_Amount_Received_Mean         0.000000
45         Canadian Dollar_Amount_Paid_Median         0.000000
44           Canadian Dollar_Amount_Paid_Mean         0.000000
43               Ruble_Amount_Received_Median         0.000000
42                 Ruble_Amount_Received_Mean         0.000000
41                   Ruble_Amount_Paid_Median         0.000000
40                     Ruble_Amount_Paid_Mean         0.000000
47     Canadian Dollar_Amount_Received_Median         0.000000
39            UK Pound_Amount_Received_Median         0.000000
48               Swiss Franc_Amount_Paid_Mean         0.000000
49             Swiss Franc_Amount_Paid_Median         0.000000
50           Swiss Franc_Amount_Received_Mean         0.000000
51         Swiss Franc_Amount_Received_Median         0.000000
52               Brazil Real_Amount_Paid_Mean         0.000000
53             Brazil Real_Amount_Paid_Median         0.000000
54           Brazil Real_Amount_Received_Mean         0.000000