In [48]:
import pandas as pd
from sklearn.model_selection import train_test_split
import optuna
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import classification_report

In [49]:
random_state = 42

In [50]:
df = pd.read_csv('../Milestone 3 EDA/ppp_cleaned.csv')
df

,ProcessingMethod,BorrowerState,LoanStatus,Term,InitialApprovalAmount,CurrentApprovalAmount,ServicingLenderState,RuralUrbanIndicator,HubzoneIndicator,LMIIndicator,...,MORTGAGE_INTEREST_PROCEED_pct,RENT_PROCEED_pct,REFINANCE_EIDL_PROCEED_pct,HEALTH_CARE_PROCEED_pct,DEBT_INTEREST_PROCEED_pct,PROCEED_Per_Job,Fraud,DateApproved_int,ForgivenessDate_int,LoanStatusDate_int
0,0.0,48.0,2.0,24,769358.78,769358.78,11.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,12409.01,0,1588291200,1605830400,1608249600
1,0.0,48.0,2.0,24,736927.79,736927.79,11.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,10094.90,0,1588291200,1628726400,1632787200
2,0.0,48.0,2.0,24,691355.00,691355.00,29.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,9218.07,0,1588291200,1612915200,1615939200
3,0.0,48.0,2.0,24,499871.00,499871.00,29.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,23803.38,0,1588291200,1631232000,1634342400
4,0.0,48.0,2.0,24,367437.00,367437.00,37.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,14697.48,0,1588291200,1617840000,1629158400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
968527,0.0,56.0,2.0,24,150000.00,150000.00,54.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,10000.00,0,1585872000,1607472000,1610496000
968528,0.0,56.0,2.0,24,150000.00,150000.00,31.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,3452.38,0,1586822400,1604361600,1607385600
968529,1.0,56.0,2.0,60,150000.00,150000.00,54.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,29999.40,0,1613088000,1629158400,1631664000
968530,0.0,56.0,2.0,60,150000.00,150000.00,18.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,21428.57,0,1586908800,1645574400,1646697600
968531,0.0,56.0,2.0,24,150000.00,150000.00,54.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,13636.36,0,1586390400,1632268800,1634860800

In [51]:
fraud = df[df['Fraud'] == 1]
non_fraud = df[df['Fraud'] == 0]
len(fraud), len(non_fraud)

(95, 968437)

In [52]:
# Undersample majority class to a 1:10 ratio
non_fraud_downsampled = non_fraud.sample(n=len(fraud) * 10, random_state=random_state)
non_fraud_downsampled

,ProcessingMethod,BorrowerState,LoanStatus,Term,InitialApprovalAmount,CurrentApprovalAmount,ServicingLenderState,RuralUrbanIndicator,HubzoneIndicator,LMIIndicator,...,MORTGAGE_INTEREST_PROCEED_pct,RENT_PROCEED_pct,REFINANCE_EIDL_PROCEED_pct,HEALTH_CARE_PROCEED_pct,DEBT_INTEREST_PROCEED_pct,PROCEED_Per_Job,Fraud,DateApproved_int,ForgivenessDate_int,LoanStatusDate_int
495859,1.0,25.0,2.0,60,175700.0,175700.0,52.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,4748.57,0,1617062400,1638835200,1641427200
751210,0.0,41.0,2.0,24,379200.0,379200.0,40.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,9248.78,0,1586390400,1611619200,1613433600
302413,0.0,14.0,2.0,24,238300.0,238300.0,14.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,8510.71,0,1586217600,1605571200,1615334400
199402,0.0,8.0,2.0,24,742528.0,742528.0,37.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,19540.21,0,1586649600,1640044800,1642809600
52948,1.0,5.0,2.0,60,882672.0,882672.0,37.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,18389.00,0,1615593600,1640131200,1642809600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
294662,0.0,13.0,2.0,24,298700.0,298700.0,13.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,21335.71,0,1586908800,1630972800,1635379200
204016,0.0,9.0,2.0,24,375100.0,375100.0,42.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,10717.14,0,1588032000,1623888000,1626912000
387773,0.0,20.0,2.0,24,603200.0,603200.0,20.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,11827.45,0,1586044800,1627948800,1631577600
378063,0.0,19.0,2.0,24,515000.0,515000.0,37.0,0.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,10510.20,0,1586995200,1614902400,1618876800
876742,0.0,47.0,2.0,24,173100.0,173100.0,46.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,4808.33,0,1588896000,1628121600,1631664000

In [53]:
# Combine and shuffle
df_reduced = pd.concat([fraud, non_fraud_downsampled]).sample(frac=1).reset_index(drop=True)
df_reduced

,ProcessingMethod,BorrowerState,LoanStatus,Term,InitialApprovalAmount,CurrentApprovalAmount,ServicingLenderState,RuralUrbanIndicator,HubzoneIndicator,LMIIndicator,...,MORTGAGE_INTEREST_PROCEED_pct,RENT_PROCEED_pct,REFINANCE_EIDL_PROCEED_pct,HEALTH_CARE_PROCEED_pct,DEBT_INTEREST_PROCEED_pct,PROCEED_Per_Job,Fraud,DateApproved_int,ForgivenessDate_int,LoanStatusDate_int
0,1.0,41.0,2.0,60,398016.00,398016.00,36.0,1.0,0.0,0.0,...,0.0,0.000,0.0,0.0,0.0,8291.94,0,1613001600,1637884800,1645142400
1,0.0,24.0,2.0,24,337600.00,337600.00,42.0,1.0,1.0,1.0,...,0.0,0.000,0.0,0.0,0.0,19858.82,0,1586908800,1604361600,1608336000
2,0.0,53.0,2.0,24,191700.00,191700.00,39.0,1.0,0.0,0.0,...,0.0,0.000,0.0,0.0,0.0,9585.00,0,1588550400,1605139200,1608336000
3,1.0,37.0,1.0,60,330658.00,330658.00,40.0,1.0,0.0,1.0,...,0.0,0.000,0.0,0.0,0.0,9447.23,0,1617321600,-2208988800,1617321600
4,0.0,47.0,1.0,40,176332.50,176332.50,5.0,1.0,0.0,1.0,...,0.0,0.000,0.0,0.0,0.0,10372.50,1,1593475200,-2208988800,1593475200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1040,0.0,34.0,2.0,24,301297.00,301297.00,40.0,1.0,0.0,0.0,...,0.0,0.125,0.0,0.0,0.0,15064.87,0,1586476800,1604361600,1607731200
1041,0.0,6.0,2.0,24,174605.00,174605.00,6.0,1.0,0.0,1.0,...,0.0,0.000,0.0,0.0,0.0,15873.18,0,1587945600,1615420800,1617926400
1042,1.0,20.0,1.0,60,209351.53,209351.53,9.0,1.0,1.0,1.0,...,0.0,0.000,0.0,0.0,0.0,16103.58,0,1617235200,-2208988800,1617235200
1043,0.0,47.0,2.0,24,558700.00,558700.00,46.0,1.0,0.0,1.0,...,0.0,0.000,0.0,0.0,0.0,7906.13,0,1586304000,1607299200,1612224000
1044,0.0,5.0,1.0,24,1000000.00,1000000.00,29.0,1.0,0.0,1.0,...,0.0,0.000,0.0,0.0,0.0,10000.00,1,1590192000,-2208988800,1590192000

In [54]:
X = df_reduced.drop(columns='Fraud')
y = df_reduced['Fraud']

In [55]:
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    test_size=0.2, 
                                                    stratify=y,  # Maintains class distribution
                                                    random_state=random_state
                                                    )

In [56]:
cv = StratifiedKFold(n_splits=5)

### Recall as metric

In [57]:
# Parameter tuning
def objective(trial):
    n_estimators = trial.suggest_int("n_estimators", 10, 200)
    max_depth = trial.suggest_int("max_depth", 2, 32, log=True)
    min_samples_split = trial.suggest_int("min_samples_split", 2, 10)
    
    model = RandomForestClassifier(
        class_weight='balanced',
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        random_state=random_state
    )
    
    scores = cross_val_score(
        model, 
        X=X_train, 
        y=y_train, 
        cv=cv,
        scoring='recall',
        n_jobs=-1,
    )
    return scores.mean()


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

top_5_recall_df = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_recall_df)

[I 2026-04-14 15:30:01,117] A new study created in memory with name: no-name-b28eea86-d191-4b47-b084-7396944ed456
[I 2026-04-14 15:30:01,205] Trial 0 finished with value: 0.9341666666666667 and parameters: {'n_estimators': 80, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:01,392] Trial 1 finished with value: 0.8683333333333334 and parameters: {'n_estimators': 187, 'max_depth': 4, 'min_samples_split': 3}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:01,550] Trial 2 finished with value: 0.9341666666666667 and parameters: {'n_estimators': 182, 'max_depth': 2, 'min_samples_split': 3}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:01,612] Trial 3 finished with value: 0.8033333333333335 and parameters: {'n_estimators': 51, 'max_depth': 21, 'min_samples_split': 7}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:01,814] Trial 4 finished with value: 0.8433333333333334 and parameters: {'n_estimators': 198, 'max_depth': 4, 'min_samples_split': 2}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:01,845] Trial 5 finished with value: 0.8033333333333335 and parameters: {'n_estimators': 15, 'max_depth': 13, 'min_samples_split': 8}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:01,939] Trial 6 finished with value: 0.8949999999999999 and parameters: {'n_estimators': 92, 'max_depth': 3, 'min_samples_split': 6}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:01,970] Trial 7 finished with value: 0.8175000000000001 and parameters: {'n_estimators': 12, 'max_depth': 25, 'min_samples_split': 10}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:02,049] Trial 8 finished with value: 0.9341666666666667 and parameters: {'n_estimators': 86, 'max_depth': 2, 'min_samples_split': 4}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:02,112] Trial 9 finished with value: 0.8949999999999999 and parameters: {'n_estimators': 60, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:02,270] Trial 10 finished with value: 0.8433333333333334 and parameters: {'n_estimators': 139, 'max_depth': 8, 'min_samples_split': 9}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:02,394] Trial 11 finished with value: 0.9341666666666667 and parameters: {'n_estimators': 138, 'max_depth': 2, 'min_samples_split': 5}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:02,553] Trial 12 finished with value: 0.8166666666666668 and parameters: {'n_estimators': 138, 'max_depth': 7, 'min_samples_split': 2}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:02,710] Trial 13 finished with value: 0.9341666666666667 and parameters: {'n_estimators': 168, 'max_depth': 2, 'min_samples_split': 4}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:02,836] Trial 14 finished with value: 0.8433333333333334 and parameters: {'n_estimators': 105, 'max_depth': 5, 'min_samples_split': 7}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:02,899] Trial 15 finished with value: 0.9341666666666667 and parameters: {'n_estimators': 59, 'max_depth': 2, 'min_samples_split': 4}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:03,072] Trial 16 finished with value: 0.8166666666666668 and parameters: {'n_estimators': 163, 'max_depth': 11, 'min_samples_split': 6}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:03,184] Trial 17 finished with value: 0.8949999999999999 and parameters: {'n_estimators': 119, 'max_depth': 3, 'min_samples_split': 3}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:03,278] Trial 18 finished with value: 0.8433333333333334 and parameters: {'n_estimators': 79, 'max_depth': 5, 'min_samples_split': 8}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:03,325] Trial 19 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 30, 'max_depth': 2, 'min_samples_split': 5}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:03,450] Trial 20 finished with value: 0.8949999999999999 and parameters: {'n_estimators': 115, 'max_depth': 3, 'min_samples_split': 3}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:03,529] Trial 21 finished with value: 0.9341666666666667 and parameters: {'n_estimators': 78, 'max_depth': 2, 'min_samples_split': 4}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:03,623] Trial 22 finished with value: 0.9341666666666667 and parameters: {'n_estimators': 84, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:03,686] Trial 23 finished with value: 0.9341666666666667 and parameters: {'n_estimators': 45, 'max_depth': 2, 'min_samples_split': 4}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:03,764] Trial 24 finished with value: 0.8433333333333334 and parameters: {'n_estimators': 70, 'max_depth': 4, 'min_samples_split': 2}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:03,860] Trial 25 finished with value: 0.8949999999999999 and parameters: {'n_estimators': 98, 'max_depth': 3, 'min_samples_split': 3}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:03,970] Trial 26 finished with value: 0.9341666666666667 and parameters: {'n_estimators': 124, 'max_depth': 2, 'min_samples_split': 5}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:04,143] Trial 27 finished with value: 0.8433333333333334 and parameters: {'n_estimators': 175, 'max_depth': 5, 'min_samples_split': 7}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:04,284] Trial 28 finished with value: 0.8949999999999999 and parameters: {'n_estimators': 153, 'max_depth': 3, 'min_samples_split': 4}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:04,473] Trial 29 finished with value: 0.8166666666666668 and parameters: {'n_estimators': 185, 'max_depth': 10, 'min_samples_split': 6}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:04,584] Trial 30 finished with value: 0.9341666666666667 and parameters: {'n_estimators': 107, 'max_depth': 2, 'min_samples_split': 3}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:04,724] Trial 31 finished with value: 0.9341666666666667 and parameters: {'n_estimators': 142, 'max_depth': 2, 'min_samples_split': 5}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:04,850] Trial 32 finished with value: 0.9341666666666667 and parameters: {'n_estimators': 129, 'max_depth': 2, 'min_samples_split': 5}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:05,054] Trial 33 finished with value: 0.8683333333333334 and parameters: {'n_estimators': 191, 'max_depth': 4, 'min_samples_split': 4}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:05,228] Trial 34 finished with value: 0.8949999999999999 and parameters: {'n_estimators': 154, 'max_depth': 3, 'min_samples_split': 2}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:05,290] Trial 35 finished with value: 0.9341666666666667 and parameters: {'n_estimators': 43, 'max_depth': 2, 'min_samples_split': 7}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:05,384] Trial 36 finished with value: 0.8683333333333334 and parameters: {'n_estimators': 89, 'max_depth': 4, 'min_samples_split': 3}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:05,602] Trial 37 finished with value: 0.8166666666666668 and parameters: {'n_estimators': 200, 'max_depth': 17, 'min_samples_split': 6}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:05,774] Trial 38 finished with value: 0.8949999999999999 and parameters: {'n_estimators': 180, 'max_depth': 3, 'min_samples_split': 8}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:05,852] Trial 39 finished with value: 0.9341666666666667 and parameters: {'n_estimators': 68, 'max_depth': 2, 'min_samples_split': 5}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:05,978] Trial 40 finished with value: 0.8433333333333334 and parameters: {'n_estimators': 98, 'max_depth': 31, 'min_samples_split': 10}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:06,135] Trial 41 finished with value: 0.9341666666666667 and parameters: {'n_estimators': 169, 'max_depth': 2, 'min_samples_split': 4}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:06,278] Trial 42 finished with value: 0.9341666666666667 and parameters: {'n_estimators': 154, 'max_depth': 2, 'min_samples_split': 4}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:06,434] Trial 43 finished with value: 0.8949999999999999 and parameters: {'n_estimators': 165, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:06,623] Trial 44 finished with value: 0.9341666666666667 and parameters: {'n_estimators': 192, 'max_depth': 2, 'min_samples_split': 3}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:06,780] Trial 45 finished with value: 0.9341666666666667 and parameters: {'n_estimators': 132, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:06,922] Trial 46 finished with value: 0.9341666666666667 and parameters: {'n_estimators': 149, 'max_depth': 2, 'min_samples_split': 4}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:07,092] Trial 47 finished with value: 0.8949999999999999 and parameters: {'n_estimators': 171, 'max_depth': 3, 'min_samples_split': 7}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:07,217] Trial 48 finished with value: 0.8166666666666668 and parameters: {'n_estimators': 111, 'max_depth': 6, 'min_samples_split': 5}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:07,358] Trial 49 finished with value: 0.8949999999999999 and parameters: {'n_estimators': 161, 'max_depth': 3, 'min_samples_split': 2}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:07,421] Trial 50 finished with value: 0.9341666666666667 and parameters: {'n_estimators': 57, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:07,499] Trial 51 finished with value: 0.9341666666666667 and parameters: {'n_estimators': 70, 'max_depth': 2, 'min_samples_split': 4}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:07,577] Trial 52 finished with value: 0.9341666666666667 and parameters: {'n_estimators': 78, 'max_depth': 2, 'min_samples_split': 4}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:07,625] Trial 53 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 34, 'max_depth': 2, 'min_samples_split': 3}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:07,688] Trial 54 finished with value: 0.8949999999999999 and parameters: {'n_estimators': 57, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:07,751] Trial 55 finished with value: 0.9341666666666667 and parameters: {'n_estimators': 63, 'max_depth': 2, 'min_samples_split': 3}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:07,845] Trial 56 finished with value: 0.9341666666666667 and parameters: {'n_estimators': 95, 'max_depth': 2, 'min_samples_split': 4}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:07,892] Trial 57 finished with value: 0.8033333333333333 and parameters: {'n_estimators': 20, 'max_depth': 15, 'min_samples_split': 5}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:07,986] Trial 58 finished with value: 0.9083333333333334 and parameters: {'n_estimators': 86, 'max_depth': 3, 'min_samples_split': 4}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:08,174] Trial 59 finished with value: 0.8041666666666668 and parameters: {'n_estimators': 182, 'max_depth': 9, 'min_samples_split': 3}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:08,270] Trial 60 finished with value: 0.9341666666666667 and parameters: {'n_estimators': 101, 'max_depth': 2, 'min_samples_split': 2}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:08,365] Trial 61 finished with value: 0.9341666666666667 and parameters: {'n_estimators': 78, 'max_depth': 2, 'min_samples_split': 4}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:08,445] Trial 62 finished with value: 0.9341666666666667 and parameters: {'n_estimators': 80, 'max_depth': 2, 'min_samples_split': 5}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:08,524] Trial 63 finished with value: 0.8433333333333334 and parameters: {'n_estimators': 49, 'max_depth': 4, 'min_samples_split': 4}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:08,603] Trial 64 finished with value: 0.9341666666666667 and parameters: {'n_estimators': 64, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:08,682] Trial 65 finished with value: 0.9341666666666667 and parameters: {'n_estimators': 73, 'max_depth': 2, 'min_samples_split': 4}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:08,808] Trial 66 finished with value: 0.9341666666666667 and parameters: {'n_estimators': 119, 'max_depth': 2, 'min_samples_split': 3}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:08,918] Trial 67 finished with value: 0.8949999999999999 and parameters: {'n_estimators': 88, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:09,076] Trial 68 finished with value: 0.9341666666666667 and parameters: {'n_estimators': 177, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:09,249] Trial 69 finished with value: 0.8949999999999999 and parameters: {'n_estimators': 192, 'max_depth': 3, 'min_samples_split': 3}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:09,374] Trial 70 finished with value: 0.9341666666666667 and parameters: {'n_estimators': 146, 'max_depth': 2, 'min_samples_split': 9}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:09,468] Trial 71 finished with value: 0.9341666666666667 and parameters: {'n_estimators': 84, 'max_depth': 2, 'min_samples_split': 7}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:09,562] Trial 72 finished with value: 0.9341666666666667 and parameters: {'n_estimators': 75, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:09,656] Trial 73 finished with value: 0.9341666666666667 and parameters: {'n_estimators': 93, 'max_depth': 2, 'min_samples_split': 5}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:09,766] Trial 74 finished with value: 0.9341666666666667 and parameters: {'n_estimators': 104, 'max_depth': 2, 'min_samples_split': 4}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:09,874] Trial 75 finished with value: 0.9341666666666667 and parameters: {'n_estimators': 109, 'max_depth': 2, 'min_samples_split': 7}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:09,952] Trial 76 finished with value: 0.9341666666666667 and parameters: {'n_estimators': 84, 'max_depth': 2, 'min_samples_split': 5}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:10,028] Trial 77 finished with value: 0.9083333333333334 and parameters: {'n_estimators': 65, 'max_depth': 3, 'min_samples_split': 6}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:10,201] Trial 78 finished with value: 0.8949999999999999 and parameters: {'n_estimators': 159, 'max_depth': 3, 'min_samples_split': 4}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:10,264] Trial 79 finished with value: 0.9341666666666667 and parameters: {'n_estimators': 52, 'max_depth': 2, 'min_samples_split': 3}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:10,326] Trial 80 finished with value: 0.8558333333333333 and parameters: {'n_estimators': 40, 'max_depth': 4, 'min_samples_split': 6}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:10,387] Trial 81 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 49, 'max_depth': 2, 'min_samples_split': 4}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:10,449] Trial 82 finished with value: 0.7775000000000001 and parameters: {'n_estimators': 42, 'max_depth': 21, 'min_samples_split': 5}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:10,575] Trial 83 finished with value: 0.9341666666666667 and parameters: {'n_estimators': 135, 'max_depth': 2, 'min_samples_split': 4}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:10,700] Trial 84 finished with value: 0.9341666666666667 and parameters: {'n_estimators': 126, 'max_depth': 2, 'min_samples_split': 5}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:10,747] Trial 85 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 30, 'max_depth': 2, 'min_samples_split': 4}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:10,826] Trial 86 finished with value: 0.9341666666666667 and parameters: {'n_estimators': 58, 'max_depth': 2, 'min_samples_split': 3}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:10,905] Trial 87 finished with value: 0.9341666666666667 and parameters: {'n_estimators': 73, 'max_depth': 2, 'min_samples_split': 4}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:10,997] Trial 88 finished with value: 0.9341666666666667 and parameters: {'n_estimators': 98, 'max_depth': 2, 'min_samples_split': 2}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:11,107] Trial 89 finished with value: 0.8166666666666668 and parameters: {'n_estimators': 90, 'max_depth': 12, 'min_samples_split': 7}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:11,296] Trial 90 finished with value: 0.8949999999999999 and parameters: {'n_estimators': 186, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:11,408] Trial 91 finished with value: 0.9341666666666667 and parameters: {'n_estimators': 125, 'max_depth': 2, 'min_samples_split': 5}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:11,519] Trial 92 finished with value: 0.9341666666666667 and parameters: {'n_estimators': 113, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:11,644] Trial 93 finished with value: 0.9341666666666667 and parameters: {'n_estimators': 143, 'max_depth': 2, 'min_samples_split': 4}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:11,802] Trial 94 finished with value: 0.9341666666666667 and parameters: {'n_estimators': 171, 'max_depth': 2, 'min_samples_split': 4}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:11,866] Trial 95 finished with value: 0.9341666666666667 and parameters: {'n_estimators': 53, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 0 with value: 0.9341666666666667.
[I 2026-04-14 15:30:11,976] Trial 96 finished with value: 0.9341666666666667 and parameters: {'n_estimators': 119, 'max_depth': 2, 'min_samples_split': 3}. Best is trial 0 with value: 0.9341666666666667.

,number,value,datetime_start,datetime_complete,duration,params_max_depth,params_min_samples_split,params_n_estimators,state
0,0,0.934167,2026-04-14 15:30:01.119071,2026-04-14 15:30:01.205715,0 days 00:00:00.086644,2,6,80,COMPLETE
2,2,0.934167,2026-04-14 15:30:01.392452,2026-04-14 15:30:01.550170,0 days 00:00:00.157718,2,3,182,COMPLETE
8,8,0.934167,2026-04-14 15:30:01.970625,2026-04-14 15:30:02.049806,0 days 00:00:00.079181,2,4,86,COMPLETE
11,11,0.934167,2026-04-14 15:30:02.270082,2026-04-14 15:30:02.394695,0 days 00:00:00.124613,2,5,138,COMPLETE
31,31,0.934167,2026-04-14 15:30:04.584067,2026-04-14 15:30:04.724643,0 days 00:00:00.140576,2,5,142,COMPLETE

In [58]:
# Train using optimal parameters
model_1 = RandomForestClassifier(
    class_weight='balanced',
    n_estimators=top_5_recall_df.head(1)['params_n_estimators'].item(),
    max_depth=top_5_recall_df.head(1)['params_max_depth'].item(),
    min_samples_split=top_5_recall_df.head(1)['params_min_samples_split'].item(),
    random_state=random_state
)
model_1.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', max_depth=2,
                       min_samples_split=6, n_estimators=80, random_state=42)

In [59]:
y_pred = model_1.predict(X_test)

In [60]:
print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.99      0.91      0.95       190
           1       0.50      0.89      0.64        19

    accuracy                           0.91       209
   macro avg       0.74      0.90      0.79       209
weighted avg       0.94      0.91      0.92       209

In [61]:
recall_model_report_df = classification_report(y_test, y_pred, output_dict=True)

## F1 as metric

In [62]:
# Parameter tuning
def objective(trial):
    n_estimators = trial.suggest_int("n_estimators", 10, 200)
    max_depth = trial.suggest_int("max_depth", 2, 32, log=True)
    min_samples_split = trial.suggest_int("min_samples_split", 2, 10)
    
    model = RandomForestClassifier(
        class_weight='balanced',
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        random_state=random_state
    )
    
    scores = cross_val_score(
        model, 
        X=X_train, 
        y=y_train, 
        cv=cv,
        scoring='f1',
        n_jobs=-1,
    )
    return scores.mean()


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

top_5_f1_df = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_f1_df)

[I 2026-04-14 15:30:12,470] A new study created in memory with name: no-name-c80a011c-051b-4721-aadd-309af9a2638a
[I 2026-04-14 15:30:12,588] Trial 0 finished with value: 0.7994660734149054 and parameters: {'n_estimators': 110, 'max_depth': 22, 'min_samples_split': 4}. Best is trial 0 with value: 0.7994660734149054.
[I 2026-04-14 15:30:12,620] Trial 1 finished with value: 0.8076267281105991 and parameters: {'n_estimators': 19, 'max_depth': 11, 'min_samples_split': 9}. Best is trial 1 with value: 0.8076267281105991.
[I 2026-04-14 15:30:12,759] Trial 2 finished with value: 0.7244027123218217 and parameters: {'n_estimators': 157, 'max_depth': 3, 'min_samples_split': 6}. Best is trial 1 with value: 0.8076267281105991.
[I 2026-04-14 15:30:12,837] Trial 3 finished with value: 0.7979641326415521 and parameters: {'n_estimators': 61, 'max_depth': 4, 'min_samples_split': 9}. Best is trial 1 with value: 0.8076267281105991.
[I 2026-04-14 15:30:12,916] Trial 4 finished with value: 0.8021479203472268 and parameters: {'n_estimators': 58, 'max_depth': 32, 'min_samples_split': 7}. Best is trial 1 with value: 0.8076267281105991.
[I 2026-04-14 15:30:13,073] Trial 5 finished with value: 0.7325898468247457 and parameters: {'n_estimators': 159, 'max_depth': 3, 'min_samples_split': 4}. Best is trial 1 with value: 0.8076267281105991.
[I 2026-04-14 15:30:13,169] Trial 6 finished with value: 0.6510408844952238 and parameters: {'n_estimators': 90, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 1 with value: 0.8076267281105991.
[I 2026-04-14 15:30:13,280] Trial 7 finished with value: 0.8073092106698073 and parameters: {'n_estimators': 94, 'max_depth': 17, 'min_samples_split': 6}. Best is trial 1 with value: 0.8076267281105991.
[I 2026-04-14 15:30:13,436] Trial 8 finished with value: 0.7940478357386033 and parameters: {'n_estimators': 148, 'max_depth': 16, 'min_samples_split': 10}. Best is trial 1 with value: 0.8076267281105991.
[I 2026-04-14 15:30:13,626] Trial 9 finished with value: 0.8021479203472268 and parameters: {'n_estimators': 197, 'max_depth': 13, 'min_samples_split': 7}. Best is trial 1 with value: 0.8076267281105991.
[I 2026-04-14 15:30:13,658] Trial 10 finished with value: 0.7975284707876475 and parameters: {'n_estimators': 13, 'max_depth': 8, 'min_samples_split': 2}. Best is trial 1 with value: 0.8076267281105991.
[I 2026-04-14 15:30:13,690] Trial 11 finished with value: 0.7885822716183247 and parameters: {'n_estimators': 13, 'max_depth': 9, 'min_samples_split': 8}. Best is trial 1 with value: 0.8076267281105991.
[I 2026-04-14 15:30:13,753] Trial 12 finished with value: 0.8076267281105991 and parameters: {'n_estimators': 50, 'max_depth': 13, 'min_samples_split': 10}. Best is trial 1 with value: 0.8076267281105991.
[I 2026-04-14 15:30:13,817] Trial 13 finished with value: 0.8038172043010754 and parameters: {'n_estimators': 47, 'max_depth': 6, 'min_samples_split': 10}. Best is trial 1 with value: 0.8076267281105991.
[I 2026-04-14 15:30:13,865] Trial 14 finished with value: 0.8076267281105991 and parameters: {'n_estimators': 37, 'max_depth': 11, 'min_samples_split': 9}. Best is trial 1 with value: 0.8076267281105991.
[I 2026-04-14 15:30:13,912] Trial 15 finished with value: 0.8019815668202765 and parameters: {'n_estimators': 31, 'max_depth': 6, 'min_samples_split': 9}. Best is trial 1 with value: 0.8076267281105991.
[I 2026-04-14 15:30:13,992] Trial 16 finished with value: 0.7993508660416335 and parameters: {'n_estimators': 73, 'max_depth': 23, 'min_samples_split': 10}. Best is trial 1 with value: 0.8076267281105991.
[I 2026-04-14 15:30:14,118] Trial 17 finished with value: 0.7961264149708827 and parameters: {'n_estimators': 121, 'max_depth': 11, 'min_samples_split': 8}. Best is trial 1 with value: 0.8076267281105991.
[I 2026-04-14 15:30:14,213] Trial 18 finished with value: 0.7955508596400438 and parameters: {'n_estimators': 77, 'max_depth': 5, 'min_samples_split': 8}. Best is trial 1 with value: 0.8076267281105991.
[I 2026-04-14 15:30:14,261] Trial 19 finished with value: 0.7888669950738916 and parameters: {'n_estimators': 30, 'max_depth': 17, 'min_samples_split': 4}. Best is trial 1 with value: 0.8076267281105991.
[I 2026-04-14 15:30:14,292] Trial 20 finished with value: 0.7847865275142315 and parameters: {'n_estimators': 13, 'max_depth': 31, 'min_samples_split': 10}. Best is trial 1 with value: 0.8076267281105991.
[I 2026-04-14 15:30:14,354] Trial 21 finished with value: 0.7994546850998464 and parameters: {'n_estimators': 36, 'max_depth': 11, 'min_samples_split': 9}. Best is trial 1 with value: 0.8076267281105991.
[I 2026-04-14 15:30:14,417] Trial 22 finished with value: 0.787369299221357 and parameters: {'n_estimators': 46, 'max_depth': 9, 'min_samples_split': 9}. Best is trial 1 with value: 0.8076267281105991.
[I 2026-04-14 15:30:14,465] Trial 23 finished with value: 0.8076267281105991 and parameters: {'n_estimators': 29, 'max_depth': 13, 'min_samples_split': 8}. Best is trial 1 with value: 0.8076267281105991.
[I 2026-04-14 15:30:14,543] Trial 24 finished with value: 0.8176818469323214 and parameters: {'n_estimators': 62, 'max_depth': 7, 'min_samples_split': 9}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:14,622] Trial 25 finished with value: 0.7961264149708827 and parameters: {'n_estimators': 62, 'max_depth': 7, 'min_samples_split': 7}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:14,731] Trial 26 finished with value: 0.7979641326415521 and parameters: {'n_estimators': 79, 'max_depth': 4, 'min_samples_split': 10}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:14,794] Trial 27 finished with value: 0.8003149001536098 and parameters: {'n_estimators': 49, 'max_depth': 22, 'min_samples_split': 9}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:14,921] Trial 28 finished with value: 0.8021479203472268 and parameters: {'n_estimators': 117, 'max_depth': 8, 'min_samples_split': 5}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:15,031] Trial 29 finished with value: 0.7953037766830869 and parameters: {'n_estimators': 102, 'max_depth': 13, 'min_samples_split': 2}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:15,110] Trial 30 finished with value: 0.7955508596400438 and parameters: {'n_estimators': 69, 'max_depth': 5, 'min_samples_split': 8}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:15,173] Trial 31 finished with value: 0.7994546850998464 and parameters: {'n_estimators': 40, 'max_depth': 11, 'min_samples_split': 9}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:15,219] Trial 32 finished with value: 0.8038172043010754 and parameters: {'n_estimators': 25, 'max_depth': 15, 'min_samples_split': 10}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:15,298] Trial 33 finished with value: 0.7993508660416335 and parameters: {'n_estimators': 52, 'max_depth': 9, 'min_samples_split': 9}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:15,346] Trial 34 finished with value: 0.7930568356374808 and parameters: {'n_estimators': 21, 'max_depth': 7, 'min_samples_split': 7}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:15,425] Trial 35 finished with value: 0.8053723714179777 and parameters: {'n_estimators': 65, 'max_depth': 20, 'min_samples_split': 9}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:15,504] Trial 36 finished with value: 0.8022517394054397 and parameters: {'n_estimators': 56, 'max_depth': 11, 'min_samples_split': 8}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:15,552] Trial 37 finished with value: 0.6546306280849674 and parameters: {'n_estimators': 38, 'max_depth': 2, 'min_samples_split': 10}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:15,600] Trial 38 finished with value: 0.7473835879342763 and parameters: {'n_estimators': 22, 'max_depth': 3, 'min_samples_split': 7}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:15,695] Trial 39 finished with value: 0.8073092106698073 and parameters: {'n_estimators': 86, 'max_depth': 26, 'min_samples_split': 5}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:15,836] Trial 40 finished with value: 0.7980814491839814 and parameters: {'n_estimators': 133, 'max_depth': 13, 'min_samples_split': 9}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:15,883] Trial 41 finished with value: 0.8114532019704435 and parameters: {'n_estimators': 24, 'max_depth': 14, 'min_samples_split': 8}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:15,915] Trial 42 finished with value: 0.7905303030303031 and parameters: {'n_estimators': 10, 'max_depth': 10, 'min_samples_split': 9}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:15,963] Trial 43 finished with value: 0.8149283154121865 and parameters: {'n_estimators': 21, 'max_depth': 15, 'min_samples_split': 10}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:15,995] Trial 44 finished with value: 0.8003149001536098 and parameters: {'n_estimators': 19, 'max_depth': 19, 'min_samples_split': 10}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:16,184] Trial 45 finished with value: 0.8094059848633558 and parameters: {'n_estimators': 180, 'max_depth': 15, 'min_samples_split': 10}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:16,388] Trial 46 finished with value: 0.8104237824161924 and parameters: {'n_estimators': 181, 'max_depth': 18, 'min_samples_split': 8}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:16,579] Trial 47 finished with value: 0.8104237824161924 and parameters: {'n_estimators': 184, 'max_depth': 15, 'min_samples_split': 8}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:16,786] Trial 48 finished with value: 0.8073092106698073 and parameters: {'n_estimators': 175, 'max_depth': 27, 'min_samples_split': 6}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:16,992] Trial 49 finished with value: 0.8021479203472268 and parameters: {'n_estimators': 195, 'max_depth': 18, 'min_samples_split': 7}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:17,181] Trial 50 finished with value: 0.8104237824161924 and parameters: {'n_estimators': 159, 'max_depth': 15, 'min_samples_split': 8}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:17,355] Trial 51 finished with value: 0.8104237824161924 and parameters: {'n_estimators': 159, 'max_depth': 15, 'min_samples_split': 8}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:17,546] Trial 52 finished with value: 0.8104237824161924 and parameters: {'n_estimators': 182, 'max_depth': 20, 'min_samples_split': 8}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:17,735] Trial 53 finished with value: 0.7961264149708827 and parameters: {'n_estimators': 172, 'max_depth': 26, 'min_samples_split': 7}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:17,926] Trial 54 finished with value: 0.8104237824161924 and parameters: {'n_estimators': 166, 'max_depth': 16, 'min_samples_split': 8}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:18,082] Trial 55 finished with value: 0.8044022770398482 and parameters: {'n_estimators': 149, 'max_depth': 14, 'min_samples_split': 8}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:18,270] Trial 56 finished with value: 0.8021479203472268 and parameters: {'n_estimators': 191, 'max_depth': 22, 'min_samples_split': 7}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:18,475] Trial 57 finished with value: 0.8044022770398482 and parameters: {'n_estimators': 186, 'max_depth': 17, 'min_samples_split': 8}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:18,616] Trial 58 finished with value: 0.7980814491839814 and parameters: {'n_estimators': 138, 'max_depth': 20, 'min_samples_split': 9}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:18,789] Trial 59 finished with value: 0.8073092106698073 and parameters: {'n_estimators': 165, 'max_depth': 12, 'min_samples_split': 6}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:18,898] Trial 60 finished with value: 0.7993508660416335 and parameters: {'n_estimators': 102, 'max_depth': 29, 'min_samples_split': 9}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:19,070] Trial 61 finished with value: 0.8044022770398482 and parameters: {'n_estimators': 154, 'max_depth': 14, 'min_samples_split': 8}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:19,241] Trial 62 finished with value: 0.8044022770398482 and parameters: {'n_estimators': 160, 'max_depth': 24, 'min_samples_split': 8}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:19,444] Trial 63 finished with value: 0.8104237824161924 and parameters: {'n_estimators': 199, 'max_depth': 16, 'min_samples_split': 8}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:19,602] Trial 64 finished with value: 0.7961264149708827 and parameters: {'n_estimators': 139, 'max_depth': 18, 'min_samples_split': 7}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:19,792] Trial 65 finished with value: 0.8033844794870116 and parameters: {'n_estimators': 172, 'max_depth': 15, 'min_samples_split': 9}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:19,980] Trial 66 finished with value: 0.8104237824161924 and parameters: {'n_estimators': 191, 'max_depth': 10, 'min_samples_split': 8}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:20,105] Trial 67 finished with value: 0.7993508660416335 and parameters: {'n_estimators': 121, 'max_depth': 12, 'min_samples_split': 9}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:20,276] Trial 68 finished with value: 0.7984714497589914 and parameters: {'n_estimators': 162, 'max_depth': 8, 'min_samples_split': 3}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:20,450] Trial 69 finished with value: 0.8064990512333965 and parameters: {'n_estimators': 151, 'max_depth': 6, 'min_samples_split': 8}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:20,606] Trial 70 finished with value: 0.7961264149708827 and parameters: {'n_estimators': 142, 'max_depth': 14, 'min_samples_split': 7}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:20,796] Trial 71 finished with value: 0.8044022770398482 and parameters: {'n_estimators': 183, 'max_depth': 20, 'min_samples_split': 8}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:20,972] Trial 72 finished with value: 0.8104237824161924 and parameters: {'n_estimators': 174, 'max_depth': 22, 'min_samples_split': 8}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:21,161] Trial 73 finished with value: 0.8104237824161924 and parameters: {'n_estimators': 180, 'max_depth': 18, 'min_samples_split': 8}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:21,348] Trial 74 finished with value: 0.8094059848633558 and parameters: {'n_estimators': 189, 'max_depth': 24, 'min_samples_split': 10}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:21,489] Trial 75 finished with value: 0.8021479203472268 and parameters: {'n_estimators': 128, 'max_depth': 20, 'min_samples_split': 5}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:21,535] Trial 76 finished with value: 0.7921863799283153 and parameters: {'n_estimators': 17, 'max_depth': 12, 'min_samples_split': 8}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:21,725] Trial 77 finished with value: 0.8176818469323214 and parameters: {'n_estimators': 167, 'max_depth': 16, 'min_samples_split': 9}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:21,786] Trial 78 finished with value: 0.7956451612903226 and parameters: {'n_estimators': 44, 'max_depth': 10, 'min_samples_split': 10}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:21,973] Trial 79 finished with value: 0.8116603415559773 and parameters: {'n_estimators': 168, 'max_depth': 16, 'min_samples_split': 9}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:22,145] Trial 80 finished with value: 0.7885799684186783 and parameters: {'n_estimators': 167, 'max_depth': 4, 'min_samples_split': 9}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:22,317] Trial 81 finished with value: 0.7980814491839814 and parameters: {'n_estimators': 146, 'max_depth': 16, 'min_samples_split': 9}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:22,492] Trial 82 finished with value: 0.8116603415559773 and parameters: {'n_estimators': 158, 'max_depth': 14, 'min_samples_split': 9}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:22,539] Trial 83 finished with value: 0.7994546850998464 and parameters: {'n_estimators': 33, 'max_depth': 17, 'min_samples_split': 9}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:22,712] Trial 84 finished with value: 0.7980814491839814 and parameters: {'n_estimators': 156, 'max_depth': 14, 'min_samples_split': 10}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:22,821] Trial 85 finished with value: 0.7993508660416335 and parameters: {'n_estimators': 95, 'max_depth': 12, 'min_samples_split': 9}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:23,007] Trial 86 finished with value: 0.8094059848633558 and parameters: {'n_estimators': 170, 'max_depth': 13, 'min_samples_split': 10}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:23,196] Trial 87 finished with value: 0.8094059848633558 and parameters: {'n_estimators': 178, 'max_depth': 16, 'min_samples_split': 9}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:23,384] Trial 88 finished with value: 0.7915172461946656 and parameters: {'n_estimators': 186, 'max_depth': 5, 'min_samples_split': 9}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:23,574] Trial 89 finished with value: 0.8094059848633558 and parameters: {'n_estimators': 177, 'max_depth': 18, 'min_samples_split': 10}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:23,682] Trial 90 finished with value: 0.6511111111111111 and parameters: {'n_estimators': 109, 'max_depth': 2, 'min_samples_split': 9}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:23,856] Trial 91 finished with value: 0.8044022770398482 and parameters: {'n_estimators': 162, 'max_depth': 15, 'min_samples_split': 8}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:24,028] Trial 92 finished with value: 0.8104237824161924 and parameters: {'n_estimators': 156, 'max_depth': 15, 'min_samples_split': 8}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:24,076] Trial 93 finished with value: 0.8076267281105991 and parameters: {'n_estimators': 25, 'max_depth': 13, 'min_samples_split': 9}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:24,168] Trial 94 finished with value: 0.7961264149708827 and parameters: {'n_estimators': 84, 'max_depth': 19, 'min_samples_split': 7}. Best is trial 24 with value: 0.8176818469323214.
[I 2026-04-14 15:30:24,342] Trial 95 finished with value: 0.8176818469323214 and parameters: {'n_estimators': 169, 'max_depth': 14, 'min_samples_split': 9}. Best is trial 24 with value: 0.8176818469323214.

,number,value,datetime_start,datetime_complete,duration,params_max_depth,params_min_samples_split,params_n_estimators,state
24,24,0.817682,2026-04-14 15:30:14.465636,2026-04-14 15:30:14.543425,0 days 00:00:00.077789,7,9,62,COMPLETE
95,95,0.817682,2026-04-14 15:30:24.168968,2026-04-14 15:30:24.342163,0 days 00:00:00.173195,14,9,169,COMPLETE
77,77,0.817682,2026-04-14 15:30:21.535497,2026-04-14 15:30:21.725060,0 days 00:00:00.189563,16,9,167,COMPLETE
43,43,0.814928,2026-04-14 15:30:15.915952,2026-04-14 15:30:15.963952,0 days 00:00:00.048000,15,10,21,COMPLETE
97,97,0.811660,2026-04-14 15:30:24.517536,2026-04-14 15:30:24.706249,0 days 00:00:00.188713,17,9,164,COMPLETE

In [63]:
# Train using optimal parameters
model_2 = RandomForestClassifier(
    class_weight='balanced',
    n_estimators=top_5_f1_df.head(1)['params_n_estimators'].item(),
    max_depth=top_5_f1_df.head(1)['params_max_depth'].item(),
    min_samples_split=top_5_f1_df.head(1)['params_min_samples_split'].item(),
    random_state=random_state
)
model_2.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', max_depth=7,
                       min_samples_split=9, n_estimators=62, random_state=42)

In [64]:
y_pred = model_2.predict(X_test)

In [65]:
print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98       190
           1       0.79      0.79      0.79        19

    accuracy                           0.96       209
   macro avg       0.88      0.88      0.88       209
weighted avg       0.96      0.96      0.96       209

In [66]:
f1_model_report_df = classification_report(y_test, y_pred, output_dict=True)

### Analyze reports

In [67]:
# 2. Convert and transpose
recall_report_df = pd.DataFrame(recall_model_report_df).transpose()
f1_report_df = pd.DataFrame(f1_model_report_df).transpose()

# 3. Combine multiple reports (e.g., adding a 'Model' column for identification)
combined_df = pd.concat([recall_report_df, f1_report_df], keys=['RF optimized for Recall', 'RF optimized for F1'])

In [68]:
combined_df

                                      precision    recall  f1-score  \
RF optimized for Recall 0              0.988571  0.910526  0.947945
                        1              0.500000  0.894737  0.641509
                        accuracy       0.909091  0.909091  0.909091
                        macro avg      0.744286  0.902632  0.794727
                        weighted avg   0.944156  0.909091  0.920087
RF optimized for F1     0              0.978947  0.978947  0.978947
                        1              0.789474  0.789474  0.789474
                        accuracy       0.961722  0.961722  0.961722
                        macro avg      0.884211  0.884211  0.884211
                        weighted avg   0.961722  0.961722  0.961722

                                         support
RF optimized for Recall 0             190.000000
                        1              19.000000
                        accuracy        0.909091
                        macro avg     209.000000
                        weighted avg  209.000000
RF optimized for F1     0             190.000000
                        1              19.000000
                        accuracy        0.961722
                        macro avg     209.000000
                        weighted avg  209.000000

In [70]:
# Recall model
importances = model_1.feature_importances_
feature_names = df.drop(columns='Fraud').columns
feature_imp_recall_df = pd.DataFrame({'Feature': feature_names, 'Gini Importance': importances}).sort_values(
    'Gini Importance', ascending=False)
feature_imp_recall_df

                          Feature  Gini Importance
24              ForgivenessAmount         0.205954
26              NotForgivenAmount         0.152107
39            ForgivenessDate_int         0.121225
27             ForgivenPercentage         0.117197
40             LoanStatusDate_int         0.104449
2                      LoanStatus         0.100486
38               DateApproved_int         0.037241
3                            Term         0.031180
37                PROCEED_Per_Job         0.031100
0                ProcessingMethod         0.027298
10         BusinessAgeDescription         0.011651
28                  TOTAL_PROCEED         0.008939
4           InitialApprovalAmount         0.007163
13              UTILITIES_PROCEED         0.007016
1                   BorrowerState         0.005604
29                   PROCEED_Diff         0.005274
16                   RENT_PROCEED         0.005085
5           CurrentApprovalAmount         0.004629
14                PAYROLL_PROCEED         0.003883
12                   JobsReported         0.003609
11                   ProjectState         0.002441
20                   BusinessType         0.002099
22                        Veteran         0.001202
6            ServicingLenderState         0.000888
33               RENT_PROCEED_pct         0.000817
18            HEALTH_CARE_PROCEED         0.000758
7             RuralUrbanIndicator         0.000433
25                   ApprovalDiff         0.000152
8                HubzoneIndicator         0.000079
21         OriginatingLenderState         0.000042
9                    LMIIndicator         0.000000
17         REFINANCE_EIDL_PROCEED         0.000000
15      MORTGAGE_INTEREST_PROCEED         0.000000
23                      NonProfit         0.000000
19          DEBT_INTEREST_PROCEED         0.000000
30          UTILITIES_PROCEED_pct         0.000000
31            PAYROLL_PROCEED_pct         0.000000
32  MORTGAGE_INTEREST_PROCEED_pct         0.000000
36      DEBT_INTEREST_PROCEED_pct         0.000000
34     REFINANCE_EIDL_PROCEED_pct         0.000000
35        HEALTH_CARE_PROCEED_pct         0.000000

In [71]:
# Recall model
importances = model_2.feature_importances_
feature_names = df.drop(columns='Fraud').columns
feature_imp_f1_df = pd.DataFrame({'Feature': feature_names, 'Gini Importance': importances}).sort_values(
    'Gini Importance', ascending=False)
feature_imp_f1_df

                          Feature  Gini Importance
24              ForgivenessAmount     1.763943e-01
26              NotForgivenAmount     1.529056e-01
39            ForgivenessDate_int     1.351834e-01
27             ForgivenPercentage     1.065363e-01
40             LoanStatusDate_int     9.683011e-02
2                      LoanStatus     7.074393e-02
38               DateApproved_int     5.664837e-02
3                            Term     2.198516e-02
0                ProcessingMethod     1.982580e-02
37                PROCEED_Per_Job     1.874965e-02
5           CurrentApprovalAmount     1.631256e-02
4           InitialApprovalAmount     1.526723e-02
14                PAYROLL_PROCEED     1.492816e-02
28                  TOTAL_PROCEED     1.281226e-02
12                   JobsReported     1.241437e-02
11                   ProjectState     9.027044e-03
29                   PROCEED_Diff     8.258468e-03
13              UTILITIES_PROCEED     7.708678e-03
1                   BorrowerState     7.647729e-03
6            ServicingLenderState     6.806886e-03
10         BusinessAgeDescription     6.137486e-03
21         OriginatingLenderState     5.970717e-03
18            HEALTH_CARE_PROCEED     4.331746e-03
33               RENT_PROCEED_pct     3.034308e-03
20                   BusinessType     2.797453e-03
25                   ApprovalDiff     1.693584e-03
9                    LMIIndicator     1.550869e-03
35        HEALTH_CARE_PROCEED_pct     1.429680e-03
22                        Veteran     1.387290e-03
30          UTILITIES_PROCEED_pct     1.248751e-03
16                   RENT_PROCEED     1.139967e-03
8                HubzoneIndicator     7.834257e-04
7             RuralUrbanIndicator     5.619751e-04
23                      NonProfit     3.479874e-04
31            PAYROLL_PROCEED_pct     2.539099e-04
36      DEBT_INTEREST_PROCEED_pct     2.159942e-04
19          DEBT_INTEREST_PROCEED     1.288679e-04
17         REFINANCE_EIDL_PROCEED     1.114863e-17
15      MORTGAGE_INTEREST_PROCEED     4.413878e-18
34     REFINANCE_EIDL_PROCEED_pct     1.895905e-19
32  MORTGAGE_INTEREST_PROCEED_pct     0.000000e+00